// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module dense_latency_ap_ufixed_ap_fixed_16_6_5_3_0_config11_0_0_0_0_0_0 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        data_0_V_read,
        data_1_V_read,
        data_2_V_read,
        data_3_V_read,
        data_4_V_read,
        data_5_V_read,
        data_6_V_read,
        data_8_V_read,
        data_9_V_read,
        data_10_V_read,
        data_11_V_read,
        data_12_V_read,
        data_13_V_read,
        data_17_V_read,
        data_18_V_read,
        data_19_V_read,
        data_20_V_read,
        data_21_V_read,
        data_22_V_read,
        data_24_V_read,
        data_25_V_read,
        data_26_V_read,
        data_28_V_read,
        data_29_V_read,
        data_31_V_read,
        ap_return_0,
        ap_return_1,
        ap_return_2,
        ap_return_3,
        ap_return_4,
        ap_ce
);

parameter    ap_ST_fsm_state1 = 3'd1;
parameter    ap_ST_fsm_state2 = 3'd2;
parameter    ap_ST_fsm_state3 = 3'd4;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [5:0] data_0_V_read;
input  [5:0] data_1_V_read;
input  [5:0] data_2_V_read;
input  [5:0] data_3_V_read;
input  [5:0] data_4_V_read;
input  [5:0] data_5_V_read;
input  [5:0] data_6_V_read;
input  [5:0] data_8_V_read;
input  [5:0] data_9_V_read;
input  [5:0] data_10_V_read;
input  [5:0] data_11_V_read;
input  [5:0] data_12_V_read;
input  [5:0] data_13_V_read;
input  [5:0] data_17_V_read;
input  [5:0] data_18_V_read;
input  [5:0] data_19_V_read;
input  [5:0] data_20_V_read;
input  [5:0] data_21_V_read;
input  [5:0] data_22_V_read;
input  [5:0] data_24_V_read;
input  [5:0] data_25_V_read;
input  [5:0] data_26_V_read;
input  [5:0] data_28_V_read;
input  [5:0] data_29_V_read;
input  [5:0] data_31_V_read;
output  [15:0] ap_return_0;
output  [15:0] ap_return_1;
output  [15:0] ap_return_2;
output  [15:0] ap_return_3;
output  [15:0] ap_return_4;
input   ap_ce;

reg ap_done;
reg ap_idle;
reg ap_ready;

(* fsm_encoding = "none" *) reg   [2:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [5:0] data_5_V_read_4_reg_1847;
reg   [10:0] trunc_ln_reg_1852;
reg   [9:0] lshr_ln708_2_reg_1857;
reg   [9:0] lshr_ln708_3_reg_1862;
reg   [9:0] lshr_ln708_7_reg_1867;
reg   [8:0] trunc_ln708_122_reg_1872;
reg   [9:0] lshr_ln708_9_reg_1877;
reg   [9:0] lshr_ln708_10_reg_1882;
wire  signed [10:0] trunc_ln708_125_fu_897_p4;
reg  signed [10:0] trunc_ln708_125_reg_1887;
reg   [9:0] lshr_ln708_12_reg_1892;
reg   [9:0] lshr_ln708_15_reg_1897;
wire   [11:0] add_ln703_fu_1099_p2;
reg   [11:0] add_ln703_reg_1902;
wire   [11:0] add_ln703_4_fu_1105_p2;
reg   [11:0] add_ln703_4_reg_1907;
wire   [11:0] add_ln703_14_fu_1111_p2;
reg   [11:0] add_ln703_14_reg_1912;
wire   [10:0] add_ln703_16_fu_1117_p2;
reg   [10:0] add_ln703_16_reg_1917;
wire   [11:0] add_ln703_19_fu_1123_p2;
reg   [11:0] add_ln703_19_reg_1922;
wire   [11:0] add_ln703_21_fu_1129_p2;
reg   [11:0] add_ln703_21_reg_1927;
wire   [11:0] add_ln703_30_fu_1135_p2;
reg   [11:0] add_ln703_30_reg_1932;
wire   [11:0] add_ln703_32_fu_1141_p2;
reg   [11:0] add_ln703_32_reg_1937;
wire   [11:0] add_ln703_33_fu_1147_p2;
reg   [11:0] add_ln703_33_reg_1942;
wire   [10:0] add_ln703_38_fu_1153_p2;
reg   [10:0] add_ln703_38_reg_1947;
wire   [12:0] add_ln703_5_fu_1503_p2;
reg   [12:0] add_ln703_5_reg_1952;
wire    ap_CS_fsm_state2;
wire   [10:0] add_ln703_6_fu_1509_p2;
reg   [10:0] add_ln703_6_reg_1957;
wire   [10:0] add_ln703_7_fu_1515_p2;
reg   [10:0] add_ln703_7_reg_1962;
wire   [11:0] add_ln703_10_fu_1521_p2;
reg   [11:0] add_ln703_10_reg_1967;
wire   [10:0] add_ln703_11_fu_1527_p2;
reg   [10:0] add_ln703_11_reg_1972;
wire   [12:0] add_ln703_15_fu_1536_p2;
reg   [12:0] add_ln703_15_reg_1977;
wire   [12:0] add_ln703_20_fu_1545_p2;
reg   [12:0] add_ln703_20_reg_1982;
wire   [12:0] add_ln703_22_fu_1554_p2;
reg   [12:0] add_ln703_22_reg_1987;
wire   [11:0] add_ln703_25_fu_1570_p2;
reg   [11:0] add_ln703_25_reg_1992;
wire   [11:0] add_ln703_27_fu_1586_p2;
reg   [11:0] add_ln703_27_reg_1997;
wire   [13:0] add_ln703_35_fu_1621_p2;
reg   [13:0] add_ln703_35_reg_2002;
wire   [11:0] add_ln703_37_fu_1637_p2;
reg   [11:0] add_ln703_37_reg_2007;
wire   [12:0] add_ln703_40_fu_1656_p2;
reg   [12:0] add_ln703_40_reg_2012;
reg   [5:0] ap_port_reg_data_2_V_read;
reg   [5:0] ap_port_reg_data_9_V_read;
reg   [5:0] ap_port_reg_data_10_V_read;
reg   [5:0] ap_port_reg_data_11_V_read;
reg   [5:0] ap_port_reg_data_17_V_read;
reg   [5:0] ap_port_reg_data_20_V_read;
reg   [5:0] ap_port_reg_data_29_V_read;
wire   [5:0] mul_ln708_fu_264_p0;
wire   [5:0] mul_ln708_1_fu_265_p0;
wire   [10:0] zext_ln1118_18_fu_756_p1;
wire   [10:0] shl_ln_fu_301_p3;
wire   [10:0] zext_ln708_fu_297_p1;
wire   [10:0] sub_ln708_fu_309_p2;
wire   [9:0] lshr_ln_fu_315_p4;
wire   [10:0] shl_ln708_s_fu_333_p3;
wire   [10:0] zext_ln1118_fu_329_p1;
wire   [10:0] sub_ln708_1_fu_341_p2;
wire   [9:0] lshr_ln708_s_fu_347_p4;
wire   [11:0] zext_ln1118_1_fu_361_p1;
wire   [11:0] sub_ln1118_fu_365_p2;
wire   [10:0] shl_ln1118_s_fu_381_p3;
wire   [11:0] zext_ln1118_2_fu_389_p1;
wire   [11:0] sub_ln1118_1_fu_393_p2;
wire   [10:0] trunc_ln708_s_fu_399_p4;
wire   [10:0] shl_ln1118_1_fu_413_p3;
wire   [11:0] zext_ln1118_3_fu_421_p1;
wire   [11:0] sub_ln1118_2_fu_425_p2;
wire   [10:0] trunc_ln708_111_fu_431_p4;
wire   [10:0] mul_ln708_fu_264_p2;
wire   [10:0] shl_ln708_3_fu_464_p3;
wire   [10:0] zext_ln1118_6_fu_460_p1;
wire   [10:0] sub_ln708_3_fu_472_p2;
wire   [11:0] zext_ln1118_7_fu_488_p1;
wire   [11:0] sub_ln1118_4_fu_492_p2;
wire   [10:0] trunc_ln708_113_fu_498_p4;
wire   [10:0] shl_ln1118_3_fu_516_p3;
wire   [11:0] zext_ln1118_9_fu_524_p1;
wire   [11:0] sub_ln1118_5_fu_528_p2;
wire   [10:0] trunc_ln708_114_fu_534_p4;
wire   [10:0] zext_ln1118_8_fu_512_p1;
wire   [10:0] sub_ln708_4_fu_548_p2;
wire   [9:0] lshr_ln708_4_fu_554_p4;
wire   [10:0] shl_ln1118_6_fu_568_p3;
wire   [11:0] zext_ln1118_12_fu_576_p1;
wire   [11:0] sub_ln1118_8_fu_580_p2;
wire   [10:0] trunc_ln708_117_fu_586_p4;
wire   [10:0] shl_ln1118_7_fu_604_p3;
wire   [11:0] zext_ln1118_14_fu_612_p1;
wire   [11:0] sub_ln1118_9_fu_616_p2;
wire   [10:0] trunc_ln708_118_fu_622_p4;
wire   [10:0] zext_ln1118_13_fu_600_p1;
wire   [10:0] sub_ln708_7_fu_636_p2;
wire   [10:0] shl_ln1118_9_fu_652_p3;
wire   [11:0] zext_ln1118_16_fu_660_p1;
wire   [11:0] sub_ln1118_11_fu_664_p2;
wire   [10:0] trunc_ln708_120_fu_670_p4;
wire   [10:0] shl_ln1118_10_fu_684_p3;
wire   [11:0] zext_ln1118_17_fu_692_p1;
wire   [11:0] sub_ln1118_12_fu_696_p2;
wire   [10:0] trunc_ln708_121_fu_702_p4;
wire   [8:0] shl_ln708_7_fu_716_p3;
wire   [6:0] shl_ln708_8_fu_728_p3;
wire   [9:0] zext_ln708_10_fu_724_p1;
wire   [9:0] zext_ln708_11_fu_736_p1;
wire   [9:0] sub_ln708_8_fu_740_p2;
wire   [10:0] shl_ln1118_11_fu_761_p3;
wire   [11:0] zext_ln1118_19_fu_769_p1;
wire   [11:0] sub_ln1118_13_fu_773_p2;
wire   [10:0] trunc_ln708_123_fu_779_p4;
wire   [10:0] sub_ln708_10_fu_793_p2;
wire   [10:0] mul_ln708_1_fu_265_p2;
wire   [10:0] shl_ln1118_12_fu_823_p3;
wire   [11:0] zext_ln1118_21_fu_831_p1;
wire   [11:0] sub_ln1118_14_fu_835_p2;
wire   [10:0] trunc_ln708_124_fu_841_p4;
wire   [10:0] zext_ln1118_20_fu_819_p1;
wire   [10:0] sub_ln708_11_fu_855_p2;
wire   [9:0] lshr_ln708_11_fu_861_p4;
wire   [10:0] shl_ln1118_13_fu_879_p3;
wire   [11:0] zext_ln1118_23_fu_887_p1;
wire   [11:0] sub_ln1118_15_fu_891_p2;
wire   [10:0] zext_ln1118_22_fu_875_p1;
wire   [10:0] sub_ln708_12_fu_911_p2;
wire   [10:0] shl_ln1118_14_fu_927_p3;
wire   [11:0] zext_ln1118_24_fu_935_p1;
wire   [11:0] sub_ln1118_16_fu_939_p2;
wire   [10:0] trunc_ln708_126_fu_945_p4;
wire   [10:0] shl_ln708_10_fu_963_p3;
wire   [10:0] zext_ln708_19_fu_959_p1;
wire   [10:0] sub_ln708_13_fu_971_p2;
wire   [9:0] lshr_ln708_13_fu_977_p4;
wire   [10:0] shl_ln708_11_fu_995_p3;
wire   [10:0] zext_ln1118_25_fu_991_p1;
wire   [10:0] sub_ln708_14_fu_1003_p2;
wire   [9:0] lshr_ln708_14_fu_1009_p4;
wire   [11:0] zext_ln1118_26_fu_1023_p1;
wire   [11:0] sub_ln1118_17_fu_1027_p2;
wire   [10:0] trunc_ln708_127_fu_1033_p4;
wire   [10:0] shl_ln1118_16_fu_1051_p3;
wire   [11:0] zext_ln1118_29_fu_1059_p1;
wire   [11:0] sub_ln1118_19_fu_1063_p2;
wire   [10:0] trunc_ln708_129_fu_1069_p4;
wire   [10:0] zext_ln1118_28_fu_1047_p1;
wire   [10:0] sub_ln708_15_fu_1083_p2;
wire  signed [11:0] sext_ln203_5_fu_544_p1;
wire  signed [11:0] sext_ln203_9_fu_632_p1;
wire  signed [11:0] sext_ln1118_fu_712_p1;
wire  signed [11:0] sext_ln1118_5_fu_789_p1;
wire  signed [11:0] sext_ln1118_6_fu_851_p1;
wire   [11:0] zext_ln203_1_fu_357_p1;
wire   [10:0] zext_ln708_4_fu_564_p1;
wire   [10:0] zext_ln708_21_fu_1019_p1;
wire  signed [11:0] sext_ln1116_1_fu_680_p1;
wire  signed [11:0] sext_ln708_1_fu_955_p1;
wire  signed [11:0] sext_ln1118_9_fu_1079_p1;
wire   [11:0] zext_ln203_fu_325_p1;
wire  signed [11:0] sext_ln203_1_fu_409_p1;
wire  signed [11:0] sext_ln203_2_fu_441_p1;
wire  signed [11:0] sext_ln203_4_fu_508_p1;
wire  signed [11:0] sext_ln203_8_fu_596_p1;
wire  signed [11:0] sext_ln1118_7_fu_907_p1;
wire  signed [11:0] sext_ln1116_2_fu_1043_p1;
wire   [10:0] zext_ln708_17_fu_871_p1;
wire   [10:0] zext_ln708_20_fu_987_p1;
wire   [6:0] shl_ln708_2_fu_1170_p3;
wire   [10:0] shl_ln708_1_fu_1162_p3;
wire   [10:0] zext_ln708_1_fu_1178_p1;
wire   [10:0] sub_ln708_2_fu_1182_p2;
wire   [9:0] lshr_ln708_1_fu_1188_p4;
wire   [10:0] shl_ln1118_2_fu_1205_p3;
wire   [11:0] zext_ln1118_5_fu_1212_p1;
wire   [11:0] sub_ln1118_3_fu_1216_p2;
wire   [10:0] trunc_ln708_112_fu_1222_p4;
wire   [10:0] shl_ln1118_4_fu_1239_p3;
wire   [11:0] zext_ln1118_10_fu_1247_p1;
wire   [11:0] sub_ln1118_6_fu_1251_p2;
wire   [10:0] trunc_ln708_115_fu_1257_p4;
wire   [10:0] shl_ln708_4_fu_1275_p3;
wire   [10:0] zext_ln708_5_fu_1271_p1;
wire   [10:0] sub_ln708_5_fu_1283_p2;
wire   [9:0] lshr_ln708_5_fu_1289_p4;
wire   [10:0] shl_ln1118_5_fu_1303_p3;
wire   [11:0] zext_ln1118_11_fu_1311_p1;
wire   [11:0] sub_ln1118_7_fu_1315_p2;
wire   [10:0] trunc_ln708_116_fu_1321_p4;
wire   [9:0] shl_ln708_5_fu_1335_p3;
wire   [6:0] shl_ln708_6_fu_1347_p3;
wire   [10:0] zext_ln708_7_fu_1343_p1;
wire   [10:0] zext_ln708_8_fu_1355_p1;
wire   [10:0] sub_ln708_6_fu_1359_p2;
wire   [9:0] lshr_ln708_6_fu_1365_p4;
wire   [10:0] shl_ln1118_8_fu_1382_p3;
wire   [11:0] zext_ln1118_15_fu_1390_p1;
wire   [11:0] sub_ln1118_10_fu_1394_p2;
wire   [10:0] trunc_ln708_119_fu_1400_p4;
wire  signed [9:0] sext_ln708_fu_1414_p1;
wire   [10:0] shl_ln708_9_fu_1425_p3;
wire   [10:0] zext_ln708_13_fu_1421_p1;
wire   [10:0] sub_ln708_9_fu_1433_p2;
wire   [9:0] lshr_ln708_8_fu_1439_p4;
wire   [10:0] shl_ln1118_15_fu_1462_p3;
wire   [11:0] zext_ln1118_27_fu_1470_p1;
wire   [11:0] sub_ln1118_18_fu_1474_p2;
wire   [10:0] trunc_ln708_128_fu_1480_p4;
wire  signed [12:0] sext_ln703_6_fu_1500_p1;
wire  signed [12:0] sext_ln703_fu_1497_p1;
wire   [10:0] zext_ln708_2_fu_1202_p1;
wire   [10:0] zext_ln708_3_fu_1236_p1;
wire   [10:0] zext_ln708_14_fu_1449_p1;
wire  signed [11:0] sext_ln203_3_fu_1232_p1;
wire  signed [11:0] sext_ln203_7_fu_1331_p1;
wire   [10:0] zext_ln708_6_fu_1299_p1;
wire  signed [12:0] sext_ln703_12_fu_1533_p1;
wire  signed [12:0] sext_ln203_6_fu_1267_p1;
wire  signed [12:0] sext_ln703_16_fu_1542_p1;
wire  signed [12:0] sext_ln1116_fu_1410_p1;
wire  signed [12:0] sext_ln703_18_fu_1551_p1;
wire  signed [12:0] sext_ln1116_3_fu_1490_p1;
wire   [10:0] zext_ln708_9_fu_1379_p1;
wire   [10:0] zext_ln708_12_fu_1417_p1;
wire   [10:0] add_ln703_24_fu_1560_p2;
wire   [11:0] zext_ln703_5_fu_1566_p1;
wire   [11:0] zext_ln203_3_fu_1375_p1;
wire   [10:0] zext_ln708_18_fu_1459_p1;
wire   [10:0] add_ln703_26_fu_1576_p2;
wire  signed [11:0] sext_ln703_21_fu_1582_p1;
wire   [11:0] zext_ln708_15_fu_1453_p1;
wire  signed [12:0] sext_ln703_25_fu_1592_p1;
wire  signed [12:0] sext_ln203_fu_1159_p1;
wire   [12:0] add_ln703_31_fu_1595_p2;
wire  signed [12:0] sext_ln703_28_fu_1608_p1;
wire  signed [12:0] sext_ln703_27_fu_1605_p1;
wire   [12:0] add_ln703_34_fu_1611_p2;
wire  signed [13:0] sext_ln703_29_fu_1617_p1;
wire  signed [13:0] sext_ln703_26_fu_1601_p1;
wire   [10:0] zext_ln708_16_fu_1456_p1;
wire   [10:0] add_ln703_36_fu_1627_p2;
wire   [11:0] zext_ln703_7_fu_1633_p1;
wire   [11:0] zext_ln203_2_fu_1198_p1;
wire   [10:0] zext_ln708_22_fu_1494_p1;
wire   [10:0] add_ln703_39_fu_1646_p2;
wire  signed [12:0] sext_ln703_31_fu_1652_p1;
wire   [12:0] zext_ln703_9_fu_1643_p1;
wire    ap_CS_fsm_state3;
wire   [11:0] zext_ln703_1_fu_1671_p1;
wire   [11:0] zext_ln703_fu_1668_p1;
wire   [11:0] add_ln703_8_fu_1674_p2;
wire   [13:0] zext_ln703_2_fu_1680_p1;
wire  signed [13:0] sext_ln703_7_fu_1665_p1;
wire   [13:0] add_ln703_9_fu_1684_p2;
wire   [12:0] zext_ln703_3_fu_1697_p1;
wire  signed [12:0] sext_ln1118_8_fu_1662_p1;
wire   [12:0] add_ln703_12_fu_1700_p2;
wire  signed [13:0] sext_ln703_10_fu_1706_p1;
wire  signed [13:0] sext_ln703_9_fu_1694_p1;
wire   [13:0] acc_1_V_fu_1710_p2;
wire   [11:0] zext_ln703_4_fu_1723_p1;
wire   [11:0] add_ln703_17_fu_1726_p2;
wire  signed [13:0] sext_ln703_14_fu_1732_p1;
wire  signed [13:0] sext_ln703_13_fu_1720_p1;
wire   [13:0] acc_2_V_fu_1736_p2;
wire  signed [13:0] sext_ln703_19_fu_1749_p1;
wire  signed [13:0] sext_ln703_17_fu_1746_p1;
wire   [13:0] add_ln703_23_fu_1752_p2;
wire  signed [13:0] sext_ln703_22_fu_1765_p1;
wire   [13:0] zext_ln703_6_fu_1762_p1;
wire   [13:0] add_ln703_28_fu_1768_p2;
wire  signed [14:0] sext_ln703_23_fu_1774_p1;
wire  signed [14:0] sext_ln703_20_fu_1758_p1;
wire   [14:0] acc_3_V_fu_1778_p2;
wire  signed [13:0] sext_ln703_32_fu_1794_p1;
wire   [13:0] zext_ln703_8_fu_1791_p1;
wire   [13:0] add_ln703_41_fu_1797_p2;
wire  signed [14:0] sext_ln703_33_fu_1803_p1;
wire  signed [14:0] sext_ln703_30_fu_1788_p1;
wire   [14:0] acc_4_V_fu_1807_p2;
wire  signed [15:0] sext_ln703_8_fu_1690_p1;
wire  signed [15:0] sext_ln703_11_fu_1716_p1;
wire  signed [15:0] sext_ln703_15_fu_1742_p1;
wire  signed [15:0] sext_ln703_24_fu_1784_p1;
wire  signed [15:0] sext_ln703_34_fu_1813_p1;
reg   [2:0] ap_NS_fsm;
wire   [10:0] mul_ln708_fu_264_p00;

// power-on initialization
initial begin
#0 ap_CS_fsm = 3'd1;
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state2))) begin
        add_ln703_10_reg_1967[11 : 4] <= add_ln703_10_fu_1521_p2[11 : 4];
        add_ln703_11_reg_1972 <= add_ln703_11_fu_1527_p2;
        add_ln703_15_reg_1977 <= add_ln703_15_fu_1536_p2;
        add_ln703_20_reg_1982[12 : 4] <= add_ln703_20_fu_1545_p2[12 : 4];
        add_ln703_22_reg_1987 <= add_ln703_22_fu_1554_p2;
        add_ln703_25_reg_1992 <= add_ln703_25_fu_1570_p2;
        add_ln703_27_reg_1997 <= add_ln703_27_fu_1586_p2;
        add_ln703_35_reg_2002[13 : 4] <= add_ln703_35_fu_1621_p2[13 : 4];
        add_ln703_37_reg_2007 <= add_ln703_37_fu_1637_p2;
        add_ln703_40_reg_2012 <= add_ln703_40_fu_1656_p2;
        add_ln703_5_reg_1952[12 : 4] <= add_ln703_5_fu_1503_p2[12 : 4];
        add_ln703_6_reg_1957 <= add_ln703_6_fu_1509_p2;
        add_ln703_7_reg_1962 <= add_ln703_7_fu_1515_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state1))) begin
        add_ln703_14_reg_1912 <= add_ln703_14_fu_1111_p2;
        add_ln703_16_reg_1917 <= add_ln703_16_fu_1117_p2;
        add_ln703_19_reg_1922[11 : 4] <= add_ln703_19_fu_1123_p2[11 : 4];
        add_ln703_21_reg_1927 <= add_ln703_21_fu_1129_p2;
        add_ln703_30_reg_1932[11 : 4] <= add_ln703_30_fu_1135_p2[11 : 4];
        add_ln703_32_reg_1937[11 : 4] <= add_ln703_32_fu_1141_p2[11 : 4];
        add_ln703_33_reg_1942[11 : 4] <= add_ln703_33_fu_1147_p2[11 : 4];
        add_ln703_38_reg_1947 <= add_ln703_38_fu_1153_p2;
        add_ln703_4_reg_1907[11 : 4] <= add_ln703_4_fu_1105_p2[11 : 4];
        add_ln703_reg_1902[11 : 4] <= add_ln703_fu_1099_p2[11 : 4];
        ap_port_reg_data_10_V_read <= data_10_V_read;
        ap_port_reg_data_11_V_read <= data_11_V_read;
        ap_port_reg_data_17_V_read <= data_17_V_read;
        ap_port_reg_data_20_V_read <= data_20_V_read;
        ap_port_reg_data_29_V_read <= data_29_V_read;
        ap_port_reg_data_2_V_read <= data_2_V_read;
        ap_port_reg_data_9_V_read <= data_9_V_read;
        data_5_V_read_4_reg_1847 <= data_5_V_read;
        lshr_ln708_10_reg_1882 <= {{mul_ln708_1_fu_265_p2[10:1]}};
        lshr_ln708_12_reg_1892 <= {{sub_ln708_12_fu_911_p2[10:1]}};
        lshr_ln708_15_reg_1897 <= {{sub_ln708_15_fu_1083_p2[10:1]}};
        lshr_ln708_2_reg_1857 <= {{mul_ln708_fu_264_p2[10:1]}};
        lshr_ln708_3_reg_1862 <= {{sub_ln708_3_fu_472_p2[10:1]}};
        lshr_ln708_7_reg_1867 <= {{sub_ln708_7_fu_636_p2[10:1]}};
        lshr_ln708_9_reg_1877 <= {{sub_ln708_10_fu_793_p2[10:1]}};
        trunc_ln708_122_reg_1872 <= {{sub_ln708_8_fu_740_p2[9:1]}};
        trunc_ln708_125_reg_1887 <= {{sub_ln1118_15_fu_891_p2[11:1]}};
        trunc_ln_reg_1852 <= {{sub_ln1118_fu_365_p2[11:1]}};
    end
end

always @ (*) begin
    if ((((1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state3)) | ((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state3))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign acc_1_V_fu_1710_p2 = ($signed(sext_ln703_10_fu_1706_p1) + $signed(sext_ln703_9_fu_1694_p1));

assign acc_2_V_fu_1736_p2 = ($signed(sext_ln703_14_fu_1732_p1) + $signed(sext_ln703_13_fu_1720_p1));

assign acc_3_V_fu_1778_p2 = ($signed(sext_ln703_23_fu_1774_p1) + $signed(sext_ln703_20_fu_1758_p1));

assign acc_4_V_fu_1807_p2 = ($signed(sext_ln703_33_fu_1803_p1) + $signed(sext_ln703_30_fu_1788_p1));

assign add_ln703_10_fu_1521_p2 = ($signed(sext_ln203_3_fu_1232_p1) + $signed(sext_ln203_7_fu_1331_p1));

assign add_ln703_11_fu_1527_p2 = (zext_ln708_6_fu_1299_p1 + 11'd992);

assign add_ln703_12_fu_1700_p2 = ($signed(zext_ln703_3_fu_1697_p1) + $signed(sext_ln1118_8_fu_1662_p1));

assign add_ln703_14_fu_1111_p2 = ($signed(sext_ln1118_6_fu_851_p1) + $signed(zext_ln203_1_fu_357_p1));

assign add_ln703_15_fu_1536_p2 = ($signed(sext_ln703_12_fu_1533_p1) + $signed(sext_ln203_6_fu_1267_p1));

assign add_ln703_16_fu_1117_p2 = (zext_ln708_4_fu_564_p1 + zext_ln708_21_fu_1019_p1);

assign add_ln703_17_fu_1726_p2 = ($signed(zext_ln703_4_fu_1723_p1) + $signed(12'd3360));

assign add_ln703_19_fu_1123_p2 = ($signed(sext_ln1116_1_fu_680_p1) + $signed(sext_ln708_1_fu_955_p1));

assign add_ln703_20_fu_1545_p2 = ($signed(sext_ln703_16_fu_1542_p1) + $signed(sext_ln1116_fu_1410_p1));

assign add_ln703_21_fu_1129_p2 = ($signed(sext_ln1118_9_fu_1079_p1) + $signed(zext_ln203_fu_325_p1));

assign add_ln703_22_fu_1554_p2 = ($signed(sext_ln703_18_fu_1551_p1) + $signed(sext_ln1116_3_fu_1490_p1));

assign add_ln703_23_fu_1752_p2 = ($signed(sext_ln703_19_fu_1749_p1) + $signed(sext_ln703_17_fu_1746_p1));

assign add_ln703_24_fu_1560_p2 = (zext_ln708_9_fu_1379_p1 + zext_ln708_12_fu_1417_p1);

assign add_ln703_25_fu_1570_p2 = (zext_ln703_5_fu_1566_p1 + zext_ln203_3_fu_1375_p1);

assign add_ln703_26_fu_1576_p2 = ($signed(zext_ln708_18_fu_1459_p1) + $signed(11'd1792));

assign add_ln703_27_fu_1586_p2 = ($signed(sext_ln703_21_fu_1582_p1) + $signed(zext_ln708_15_fu_1453_p1));

assign add_ln703_28_fu_1768_p2 = ($signed(sext_ln703_22_fu_1765_p1) + $signed(zext_ln703_6_fu_1762_p1));

assign add_ln703_30_fu_1135_p2 = ($signed(sext_ln203_1_fu_409_p1) + $signed(sext_ln203_2_fu_441_p1));

assign add_ln703_31_fu_1595_p2 = ($signed(sext_ln703_25_fu_1592_p1) + $signed(sext_ln203_fu_1159_p1));

assign add_ln703_32_fu_1141_p2 = ($signed(sext_ln203_4_fu_508_p1) + $signed(sext_ln203_8_fu_596_p1));

assign add_ln703_33_fu_1147_p2 = ($signed(sext_ln1118_7_fu_907_p1) + $signed(sext_ln1116_2_fu_1043_p1));

assign add_ln703_34_fu_1611_p2 = ($signed(sext_ln703_28_fu_1608_p1) + $signed(sext_ln703_27_fu_1605_p1));

assign add_ln703_35_fu_1621_p2 = ($signed(sext_ln703_29_fu_1617_p1) + $signed(sext_ln703_26_fu_1601_p1));

assign add_ln703_36_fu_1627_p2 = (zext_ln708_9_fu_1379_p1 + zext_ln708_16_fu_1456_p1);

assign add_ln703_37_fu_1637_p2 = (zext_ln703_7_fu_1633_p1 + zext_ln203_2_fu_1198_p1);

assign add_ln703_38_fu_1153_p2 = (zext_ln708_17_fu_871_p1 + zext_ln708_20_fu_987_p1);

assign add_ln703_39_fu_1646_p2 = ($signed(zext_ln708_22_fu_1494_p1) + $signed(11'd1632));

assign add_ln703_40_fu_1656_p2 = ($signed(sext_ln703_31_fu_1652_p1) + $signed(zext_ln703_9_fu_1643_p1));

assign add_ln703_41_fu_1797_p2 = ($signed(sext_ln703_32_fu_1794_p1) + $signed(zext_ln703_8_fu_1791_p1));

assign add_ln703_4_fu_1105_p2 = ($signed(sext_ln1118_fu_712_p1) + $signed(sext_ln1118_5_fu_789_p1));

assign add_ln703_5_fu_1503_p2 = ($signed(sext_ln703_6_fu_1500_p1) + $signed(sext_ln703_fu_1497_p1));

assign add_ln703_6_fu_1509_p2 = (zext_ln708_2_fu_1202_p1 + zext_ln708_3_fu_1236_p1);

assign add_ln703_7_fu_1515_p2 = (zext_ln708_14_fu_1449_p1 + 11'd32);

assign add_ln703_8_fu_1674_p2 = (zext_ln703_1_fu_1671_p1 + zext_ln703_fu_1668_p1);

assign add_ln703_9_fu_1684_p2 = ($signed(zext_ln703_2_fu_1680_p1) + $signed(sext_ln703_7_fu_1665_p1));

assign add_ln703_fu_1099_p2 = ($signed(sext_ln203_5_fu_544_p1) + $signed(sext_ln203_9_fu_632_p1));

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_return_0 = sext_ln703_8_fu_1690_p1;

assign ap_return_1 = sext_ln703_11_fu_1716_p1;

assign ap_return_2 = sext_ln703_15_fu_1742_p1;

assign ap_return_3 = sext_ln703_24_fu_1784_p1;

assign ap_return_4 = sext_ln703_34_fu_1813_p1;

assign lshr_ln708_11_fu_861_p4 = {{sub_ln708_11_fu_855_p2[10:1]}};

assign lshr_ln708_13_fu_977_p4 = {{sub_ln708_13_fu_971_p2[10:1]}};

assign lshr_ln708_14_fu_1009_p4 = {{sub_ln708_14_fu_1003_p2[10:1]}};

assign lshr_ln708_1_fu_1188_p4 = {{sub_ln708_2_fu_1182_p2[10:1]}};

assign lshr_ln708_4_fu_554_p4 = {{sub_ln708_4_fu_548_p2[10:1]}};

assign lshr_ln708_5_fu_1289_p4 = {{sub_ln708_5_fu_1283_p2[10:1]}};

assign lshr_ln708_6_fu_1365_p4 = {{sub_ln708_6_fu_1359_p2[10:1]}};

assign lshr_ln708_8_fu_1439_p4 = {{sub_ln708_9_fu_1433_p2[10:1]}};

assign lshr_ln708_s_fu_347_p4 = {{sub_ln708_1_fu_341_p2[10:1]}};

assign lshr_ln_fu_315_p4 = {{sub_ln708_fu_309_p2[10:1]}};

assign mul_ln708_1_fu_265_p0 = zext_ln1118_18_fu_756_p1;

assign mul_ln708_1_fu_265_p2 = (mul_ln708_1_fu_265_p0 * $signed('h17));

assign mul_ln708_fu_264_p0 = mul_ln708_fu_264_p00;

assign mul_ln708_fu_264_p00 = data_5_V_read;

assign mul_ln708_fu_264_p2 = (mul_ln708_fu_264_p0 * $signed('h1B));

assign sext_ln1116_1_fu_680_p1 = $signed(trunc_ln708_120_fu_670_p4);

assign sext_ln1116_2_fu_1043_p1 = $signed(trunc_ln708_127_fu_1033_p4);

assign sext_ln1116_3_fu_1490_p1 = $signed(trunc_ln708_128_fu_1480_p4);

assign sext_ln1116_fu_1410_p1 = $signed(trunc_ln708_119_fu_1400_p4);

assign sext_ln1118_5_fu_789_p1 = $signed(trunc_ln708_123_fu_779_p4);

assign sext_ln1118_6_fu_851_p1 = $signed(trunc_ln708_124_fu_841_p4);

assign sext_ln1118_7_fu_907_p1 = trunc_ln708_125_fu_897_p4;

assign sext_ln1118_8_fu_1662_p1 = trunc_ln708_125_reg_1887;

assign sext_ln1118_9_fu_1079_p1 = $signed(trunc_ln708_129_fu_1069_p4);

assign sext_ln1118_fu_712_p1 = $signed(trunc_ln708_121_fu_702_p4);

assign sext_ln203_1_fu_409_p1 = $signed(trunc_ln708_s_fu_399_p4);

assign sext_ln203_2_fu_441_p1 = $signed(trunc_ln708_111_fu_431_p4);

assign sext_ln203_3_fu_1232_p1 = $signed(trunc_ln708_112_fu_1222_p4);

assign sext_ln203_4_fu_508_p1 = $signed(trunc_ln708_113_fu_498_p4);

assign sext_ln203_5_fu_544_p1 = $signed(trunc_ln708_114_fu_534_p4);

assign sext_ln203_6_fu_1267_p1 = $signed(trunc_ln708_115_fu_1257_p4);

assign sext_ln203_7_fu_1331_p1 = $signed(trunc_ln708_116_fu_1321_p4);

assign sext_ln203_8_fu_596_p1 = $signed(trunc_ln708_117_fu_586_p4);

assign sext_ln203_9_fu_632_p1 = $signed(trunc_ln708_118_fu_622_p4);

assign sext_ln203_fu_1159_p1 = $signed(trunc_ln_reg_1852);

assign sext_ln703_10_fu_1706_p1 = $signed(add_ln703_12_fu_1700_p2);

assign sext_ln703_11_fu_1716_p1 = $signed(acc_1_V_fu_1710_p2);

assign sext_ln703_12_fu_1533_p1 = $signed(add_ln703_14_reg_1912);

assign sext_ln703_13_fu_1720_p1 = $signed(add_ln703_15_reg_1977);

assign sext_ln703_14_fu_1732_p1 = $signed(add_ln703_17_fu_1726_p2);

assign sext_ln703_15_fu_1742_p1 = $signed(acc_2_V_fu_1736_p2);

assign sext_ln703_16_fu_1542_p1 = $signed(add_ln703_19_reg_1922);

assign sext_ln703_17_fu_1746_p1 = $signed(add_ln703_20_reg_1982);

assign sext_ln703_18_fu_1551_p1 = $signed(add_ln703_21_reg_1927);

assign sext_ln703_19_fu_1749_p1 = $signed(add_ln703_22_reg_1987);

assign sext_ln703_20_fu_1758_p1 = $signed(add_ln703_23_fu_1752_p2);

assign sext_ln703_21_fu_1582_p1 = $signed(add_ln703_26_fu_1576_p2);

assign sext_ln703_22_fu_1765_p1 = $signed(add_ln703_27_reg_1997);

assign sext_ln703_23_fu_1774_p1 = $signed(add_ln703_28_fu_1768_p2);

assign sext_ln703_24_fu_1784_p1 = $signed(acc_3_V_fu_1778_p2);

assign sext_ln703_25_fu_1592_p1 = $signed(add_ln703_30_reg_1932);

assign sext_ln703_26_fu_1601_p1 = $signed(add_ln703_31_fu_1595_p2);

assign sext_ln703_27_fu_1605_p1 = $signed(add_ln703_32_reg_1937);

assign sext_ln703_28_fu_1608_p1 = $signed(add_ln703_33_reg_1942);

assign sext_ln703_29_fu_1617_p1 = $signed(add_ln703_34_fu_1611_p2);

assign sext_ln703_30_fu_1788_p1 = $signed(add_ln703_35_reg_2002);

assign sext_ln703_31_fu_1652_p1 = $signed(add_ln703_39_fu_1646_p2);

assign sext_ln703_32_fu_1794_p1 = $signed(add_ln703_40_reg_2012);

assign sext_ln703_33_fu_1803_p1 = $signed(add_ln703_41_fu_1797_p2);

assign sext_ln703_34_fu_1813_p1 = $signed(acc_4_V_fu_1807_p2);

assign sext_ln703_6_fu_1500_p1 = $signed(add_ln703_4_reg_1907);

assign sext_ln703_7_fu_1665_p1 = $signed(add_ln703_5_reg_1952);

assign sext_ln703_8_fu_1690_p1 = $signed(add_ln703_9_fu_1684_p2);

assign sext_ln703_9_fu_1694_p1 = $signed(add_ln703_10_reg_1967);

assign sext_ln703_fu_1497_p1 = $signed(add_ln703_reg_1902);

assign sext_ln708_1_fu_955_p1 = $signed(trunc_ln708_126_fu_945_p4);

assign sext_ln708_fu_1414_p1 = $signed(trunc_ln708_122_reg_1872);

assign shl_ln1118_10_fu_684_p3 = {{data_19_V_read}, {5'd0}};

assign shl_ln1118_11_fu_761_p3 = {{data_21_V_read}, {5'd0}};

assign shl_ln1118_12_fu_823_p3 = {{data_22_V_read}, {5'd0}};

assign shl_ln1118_13_fu_879_p3 = {{data_24_V_read}, {5'd0}};

assign shl_ln1118_14_fu_927_p3 = {{data_25_V_read}, {5'd0}};

assign shl_ln1118_15_fu_1462_p3 = {{ap_port_reg_data_29_V_read}, {5'd0}};

assign shl_ln1118_16_fu_1051_p3 = {{data_31_V_read}, {5'd0}};

assign shl_ln1118_1_fu_413_p3 = {{data_4_V_read}, {5'd0}};

assign shl_ln1118_2_fu_1205_p3 = {{data_5_V_read_4_reg_1847}, {5'd0}};

assign shl_ln1118_3_fu_516_p3 = {{data_8_V_read}, {5'd0}};

assign shl_ln1118_4_fu_1239_p3 = {{ap_port_reg_data_9_V_read}, {5'd0}};

assign shl_ln1118_5_fu_1303_p3 = {{ap_port_reg_data_11_V_read}, {5'd0}};

assign shl_ln1118_6_fu_568_p3 = {{data_12_V_read}, {5'd0}};

assign shl_ln1118_7_fu_604_p3 = {{data_13_V_read}, {5'd0}};

assign shl_ln1118_8_fu_1382_p3 = {{ap_port_reg_data_17_V_read}, {5'd0}};

assign shl_ln1118_9_fu_652_p3 = {{data_18_V_read}, {5'd0}};

assign shl_ln1118_s_fu_381_p3 = {{data_3_V_read}, {5'd0}};

assign shl_ln708_10_fu_963_p3 = {{data_26_V_read}, {5'd0}};

assign shl_ln708_11_fu_995_p3 = {{data_28_V_read}, {5'd0}};

assign shl_ln708_1_fu_1162_p3 = {{ap_port_reg_data_2_V_read}, {5'd0}};

assign shl_ln708_2_fu_1170_p3 = {{ap_port_reg_data_2_V_read}, {1'd0}};

assign shl_ln708_3_fu_464_p3 = {{data_6_V_read}, {5'd0}};

assign shl_ln708_4_fu_1275_p3 = {{ap_port_reg_data_10_V_read}, {5'd0}};

assign shl_ln708_5_fu_1335_p3 = {{ap_port_reg_data_11_V_read}, {4'd0}};

assign shl_ln708_6_fu_1347_p3 = {{ap_port_reg_data_11_V_read}, {1'd0}};

assign shl_ln708_7_fu_716_p3 = {{data_19_V_read}, {3'd0}};

assign shl_ln708_8_fu_728_p3 = {{data_19_V_read}, {1'd0}};

assign shl_ln708_9_fu_1425_p3 = {{ap_port_reg_data_20_V_read}, {5'd0}};

assign shl_ln708_s_fu_333_p3 = {{data_1_V_read}, {5'd0}};

assign shl_ln_fu_301_p3 = {{data_0_V_read}, {5'd0}};

assign sub_ln1118_10_fu_1394_p2 = (12'd0 - zext_ln1118_15_fu_1390_p1);

assign sub_ln1118_11_fu_664_p2 = (12'd0 - zext_ln1118_16_fu_660_p1);

assign sub_ln1118_12_fu_696_p2 = (12'd0 - zext_ln1118_17_fu_692_p1);

assign sub_ln1118_13_fu_773_p2 = (12'd0 - zext_ln1118_19_fu_769_p1);

assign sub_ln1118_14_fu_835_p2 = (12'd0 - zext_ln1118_21_fu_831_p1);

assign sub_ln1118_15_fu_891_p2 = (12'd0 - zext_ln1118_23_fu_887_p1);

assign sub_ln1118_16_fu_939_p2 = (12'd0 - zext_ln1118_24_fu_935_p1);

assign sub_ln1118_17_fu_1027_p2 = (12'd0 - zext_ln1118_26_fu_1023_p1);

assign sub_ln1118_18_fu_1474_p2 = (12'd0 - zext_ln1118_27_fu_1470_p1);

assign sub_ln1118_19_fu_1063_p2 = (12'd0 - zext_ln1118_29_fu_1059_p1);

assign sub_ln1118_1_fu_393_p2 = (12'd0 - zext_ln1118_2_fu_389_p1);

assign sub_ln1118_2_fu_425_p2 = (12'd0 - zext_ln1118_3_fu_421_p1);

assign sub_ln1118_3_fu_1216_p2 = (12'd0 - zext_ln1118_5_fu_1212_p1);

assign sub_ln1118_4_fu_492_p2 = (12'd0 - zext_ln1118_7_fu_488_p1);

assign sub_ln1118_5_fu_528_p2 = (12'd0 - zext_ln1118_9_fu_524_p1);

assign sub_ln1118_6_fu_1251_p2 = (12'd0 - zext_ln1118_10_fu_1247_p1);

assign sub_ln1118_7_fu_1315_p2 = (12'd0 - zext_ln1118_11_fu_1311_p1);

assign sub_ln1118_8_fu_580_p2 = (12'd0 - zext_ln1118_12_fu_576_p1);

assign sub_ln1118_9_fu_616_p2 = (12'd0 - zext_ln1118_14_fu_612_p1);

assign sub_ln1118_fu_365_p2 = (12'd0 - zext_ln1118_1_fu_361_p1);

assign sub_ln708_10_fu_793_p2 = (shl_ln1118_11_fu_761_p3 - zext_ln1118_18_fu_756_p1);

assign sub_ln708_11_fu_855_p2 = (shl_ln1118_12_fu_823_p3 - zext_ln1118_20_fu_819_p1);

assign sub_ln708_12_fu_911_p2 = (shl_ln1118_13_fu_879_p3 - zext_ln1118_22_fu_875_p1);

assign sub_ln708_13_fu_971_p2 = (shl_ln708_10_fu_963_p3 - zext_ln708_19_fu_959_p1);

assign sub_ln708_14_fu_1003_p2 = (shl_ln708_11_fu_995_p3 - zext_ln1118_25_fu_991_p1);

assign sub_ln708_15_fu_1083_p2 = (shl_ln1118_16_fu_1051_p3 - zext_ln1118_28_fu_1047_p1);

assign sub_ln708_1_fu_341_p2 = (shl_ln708_s_fu_333_p3 - zext_ln1118_fu_329_p1);

assign sub_ln708_2_fu_1182_p2 = (shl_ln708_1_fu_1162_p3 - zext_ln708_1_fu_1178_p1);

assign sub_ln708_3_fu_472_p2 = (shl_ln708_3_fu_464_p3 - zext_ln1118_6_fu_460_p1);

assign sub_ln708_4_fu_548_p2 = (shl_ln1118_3_fu_516_p3 - zext_ln1118_8_fu_512_p1);

assign sub_ln708_5_fu_1283_p2 = (shl_ln708_4_fu_1275_p3 - zext_ln708_5_fu_1271_p1);

assign sub_ln708_6_fu_1359_p2 = (zext_ln708_7_fu_1343_p1 - zext_ln708_8_fu_1355_p1);

assign sub_ln708_7_fu_636_p2 = (shl_ln1118_7_fu_604_p3 - zext_ln1118_13_fu_600_p1);

assign sub_ln708_8_fu_740_p2 = (zext_ln708_10_fu_724_p1 - zext_ln708_11_fu_736_p1);

assign sub_ln708_9_fu_1433_p2 = (shl_ln708_9_fu_1425_p3 - zext_ln708_13_fu_1421_p1);

assign sub_ln708_fu_309_p2 = (shl_ln_fu_301_p3 - zext_ln708_fu_297_p1);

assign trunc_ln708_111_fu_431_p4 = {{sub_ln1118_2_fu_425_p2[11:1]}};

assign trunc_ln708_112_fu_1222_p4 = {{sub_ln1118_3_fu_1216_p2[11:1]}};

assign trunc_ln708_113_fu_498_p4 = {{sub_ln1118_4_fu_492_p2[11:1]}};

assign trunc_ln708_114_fu_534_p4 = {{sub_ln1118_5_fu_528_p2[11:1]}};

assign trunc_ln708_115_fu_1257_p4 = {{sub_ln1118_6_fu_1251_p2[11:1]}};

assign trunc_ln708_116_fu_1321_p4 = {{sub_ln1118_7_fu_1315_p2[11:1]}};

assign trunc_ln708_117_fu_586_p4 = {{sub_ln1118_8_fu_580_p2[11:1]}};

assign trunc_ln708_118_fu_622_p4 = {{sub_ln1118_9_fu_616_p2[11:1]}};

assign trunc_ln708_119_fu_1400_p4 = {{sub_ln1118_10_fu_1394_p2[11:1]}};

assign trunc_ln708_120_fu_670_p4 = {{sub_ln1118_11_fu_664_p2[11:1]}};

assign trunc_ln708_121_fu_702_p4 = {{sub_ln1118_12_fu_696_p2[11:1]}};

assign trunc_ln708_123_fu_779_p4 = {{sub_ln1118_13_fu_773_p2[11:1]}};

assign trunc_ln708_124_fu_841_p4 = {{sub_ln1118_14_fu_835_p2[11:1]}};

assign trunc_ln708_125_fu_897_p4 = {{sub_ln1118_15_fu_891_p2[11:1]}};

assign trunc_ln708_126_fu_945_p4 = {{sub_ln1118_16_fu_939_p2[11:1]}};

assign trunc_ln708_127_fu_1033_p4 = {{sub_ln1118_17_fu_1027_p2[11:1]}};

assign trunc_ln708_128_fu_1480_p4 = {{sub_ln1118_18_fu_1474_p2[11:1]}};

assign trunc_ln708_129_fu_1069_p4 = {{sub_ln1118_19_fu_1063_p2[11:1]}};

assign trunc_ln708_s_fu_399_p4 = {{sub_ln1118_1_fu_393_p2[11:1]}};

assign zext_ln1118_10_fu_1247_p1 = shl_ln1118_4_fu_1239_p3;

assign zext_ln1118_11_fu_1311_p1 = shl_ln1118_5_fu_1303_p3;

assign zext_ln1118_12_fu_576_p1 = shl_ln1118_6_fu_568_p3;

assign zext_ln1118_13_fu_600_p1 = data_13_V_read;

assign zext_ln1118_14_fu_612_p1 = shl_ln1118_7_fu_604_p3;

assign zext_ln1118_15_fu_1390_p1 = shl_ln1118_8_fu_1382_p3;

assign zext_ln1118_16_fu_660_p1 = shl_ln1118_9_fu_652_p3;

assign zext_ln1118_17_fu_692_p1 = shl_ln1118_10_fu_684_p3;

assign zext_ln1118_18_fu_756_p1 = data_21_V_read;

assign zext_ln1118_19_fu_769_p1 = shl_ln1118_11_fu_761_p3;

assign zext_ln1118_1_fu_361_p1 = shl_ln708_s_fu_333_p3;

assign zext_ln1118_20_fu_819_p1 = data_22_V_read;

assign zext_ln1118_21_fu_831_p1 = shl_ln1118_12_fu_823_p3;

assign zext_ln1118_22_fu_875_p1 = data_24_V_read;

assign zext_ln1118_23_fu_887_p1 = shl_ln1118_13_fu_879_p3;

assign zext_ln1118_24_fu_935_p1 = shl_ln1118_14_fu_927_p3;

assign zext_ln1118_25_fu_991_p1 = data_28_V_read;

assign zext_ln1118_26_fu_1023_p1 = shl_ln708_11_fu_995_p3;

assign zext_ln1118_27_fu_1470_p1 = shl_ln1118_15_fu_1462_p3;

assign zext_ln1118_28_fu_1047_p1 = data_31_V_read;

assign zext_ln1118_29_fu_1059_p1 = shl_ln1118_16_fu_1051_p3;

assign zext_ln1118_2_fu_389_p1 = shl_ln1118_s_fu_381_p3;

assign zext_ln1118_3_fu_421_p1 = shl_ln1118_1_fu_413_p3;

assign zext_ln1118_5_fu_1212_p1 = shl_ln1118_2_fu_1205_p3;

assign zext_ln1118_6_fu_460_p1 = data_6_V_read;

assign zext_ln1118_7_fu_488_p1 = shl_ln708_3_fu_464_p3;

assign zext_ln1118_8_fu_512_p1 = data_8_V_read;

assign zext_ln1118_9_fu_524_p1 = shl_ln1118_3_fu_516_p3;

assign zext_ln1118_fu_329_p1 = data_1_V_read;

assign zext_ln203_1_fu_357_p1 = lshr_ln708_s_fu_347_p4;

assign zext_ln203_2_fu_1198_p1 = lshr_ln708_1_fu_1188_p4;

assign zext_ln203_3_fu_1375_p1 = lshr_ln708_6_fu_1365_p4;

assign zext_ln203_fu_325_p1 = lshr_ln_fu_315_p4;

assign zext_ln703_1_fu_1671_p1 = add_ln703_7_reg_1962;

assign zext_ln703_2_fu_1680_p1 = add_ln703_8_fu_1674_p2;

assign zext_ln703_3_fu_1697_p1 = add_ln703_11_reg_1972;

assign zext_ln703_4_fu_1723_p1 = add_ln703_16_reg_1917;

assign zext_ln703_5_fu_1566_p1 = add_ln703_24_fu_1560_p2;

assign zext_ln703_6_fu_1762_p1 = add_ln703_25_reg_1992;

assign zext_ln703_7_fu_1633_p1 = add_ln703_36_fu_1627_p2;

assign zext_ln703_8_fu_1791_p1 = add_ln703_37_reg_2007;

assign zext_ln703_9_fu_1643_p1 = add_ln703_38_reg_1947;

assign zext_ln703_fu_1668_p1 = add_ln703_6_reg_1957;

assign zext_ln708_10_fu_724_p1 = shl_ln708_7_fu_716_p3;

assign zext_ln708_11_fu_736_p1 = shl_ln708_8_fu_728_p3;

assign zext_ln708_12_fu_1417_p1 = $unsigned(sext_ln708_fu_1414_p1);

assign zext_ln708_13_fu_1421_p1 = ap_port_reg_data_20_V_read;

assign zext_ln708_14_fu_1449_p1 = lshr_ln708_8_fu_1439_p4;

assign zext_ln708_15_fu_1453_p1 = lshr_ln708_9_reg_1877;

assign zext_ln708_16_fu_1456_p1 = lshr_ln708_10_reg_1882;

assign zext_ln708_17_fu_871_p1 = lshr_ln708_11_fu_861_p4;

assign zext_ln708_18_fu_1459_p1 = lshr_ln708_12_reg_1892;

assign zext_ln708_19_fu_959_p1 = data_26_V_read;

assign zext_ln708_1_fu_1178_p1 = shl_ln708_2_fu_1170_p3;

assign zext_ln708_20_fu_987_p1 = lshr_ln708_13_fu_977_p4;

assign zext_ln708_21_fu_1019_p1 = lshr_ln708_14_fu_1009_p4;

assign zext_ln708_22_fu_1494_p1 = lshr_ln708_15_reg_1897;

assign zext_ln708_2_fu_1202_p1 = lshr_ln708_2_reg_1857;

assign zext_ln708_3_fu_1236_p1 = lshr_ln708_3_reg_1862;

assign zext_ln708_4_fu_564_p1 = lshr_ln708_4_fu_554_p4;

assign zext_ln708_5_fu_1271_p1 = ap_port_reg_data_10_V_read;

assign zext_ln708_6_fu_1299_p1 = lshr_ln708_5_fu_1289_p4;

assign zext_ln708_7_fu_1343_p1 = shl_ln708_5_fu_1335_p3;

assign zext_ln708_8_fu_1355_p1 = shl_ln708_6_fu_1347_p3;

assign zext_ln708_9_fu_1379_p1 = lshr_ln708_7_reg_1867;

assign zext_ln708_fu_297_p1 = data_0_V_read;

always @ (posedge ap_clk) begin
    add_ln703_reg_1902[3:0] <= 4'b0000;
    add_ln703_4_reg_1907[3:0] <= 4'b0000;
    add_ln703_19_reg_1922[3:0] <= 4'b0000;
    add_ln703_30_reg_1932[3:0] <= 4'b0000;
    add_ln703_32_reg_1937[3:0] <= 4'b0000;
    add_ln703_33_reg_1942[3:0] <= 4'b0000;
    add_ln703_5_reg_1952[3:0] <= 4'b0000;
    add_ln703_10_reg_1967[3:0] <= 4'b0000;
    add_ln703_20_reg_1982[3:0] <= 4'b0000;
    add_ln703_35_reg_2002[3:0] <= 4'b0000;
end

endmodule //dense_latency_ap_ufixed_ap_fixed_16_6_5_3_0_config11_0_0_0_0_0_0
