-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
-- Version: 2019.2
-- Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity softmax_stable_ap_fixed_ap_fixed_16_6_5_3_0_softmax_config13_s is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    ap_ce : IN STD_LOGIC;
    data_0_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    data_1_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    data_2_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    data_3_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    data_4_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    ap_return_0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_1 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_2 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_3 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_4 : OUT STD_LOGIC_VECTOR (15 downto 0) );
end;


architecture behav of softmax_stable_ap_fixed_ap_fixed_16_6_5_3_0_softmax_config13_s is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv10_1FF : STD_LOGIC_VECTOR (9 downto 0) := "0111111111";
    constant ap_const_lv10_200 : STD_LOGIC_VECTOR (9 downto 0) := "1000000000";
    constant ap_const_lv32_11 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010001";
    constant ap_const_lv18_1FFFF : STD_LOGIC_VECTOR (17 downto 0) := "011111111111111111";
    constant ap_const_lv32_12 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010010";
    constant ap_const_lv18_20000 : STD_LOGIC_VECTOR (17 downto 0) := "100000000000000000";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv32_19 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011001";

    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_state4_pp0_stage0_iter3 : BOOLEAN;
    signal ap_block_state5_pp0_stage0_iter4 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal exp_table1_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal exp_table1_ce0 : STD_LOGIC;
    signal exp_table1_q0 : STD_LOGIC_VECTOR (16 downto 0);
    signal exp_table1_address1 : STD_LOGIC_VECTOR (9 downto 0);
    signal exp_table1_ce1 : STD_LOGIC;
    signal exp_table1_q1 : STD_LOGIC_VECTOR (16 downto 0);
    signal exp_table1_address2 : STD_LOGIC_VECTOR (9 downto 0);
    signal exp_table1_ce2 : STD_LOGIC;
    signal exp_table1_q2 : STD_LOGIC_VECTOR (16 downto 0);
    signal exp_table1_address3 : STD_LOGIC_VECTOR (9 downto 0);
    signal exp_table1_ce3 : STD_LOGIC;
    signal exp_table1_q3 : STD_LOGIC_VECTOR (16 downto 0);
    signal exp_table1_address4 : STD_LOGIC_VECTOR (9 downto 0);
    signal exp_table1_ce4 : STD_LOGIC;
    signal exp_table1_q4 : STD_LOGIC_VECTOR (16 downto 0);
    signal invert_table2_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal invert_table2_ce0 : STD_LOGIC;
    signal invert_table2_q0 : STD_LOGIC_VECTOR (17 downto 0);
    signal y_V_fu_538_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal y_V_reg_1088 : STD_LOGIC_VECTOR (9 downto 0);
    signal y_V_1_fu_572_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal y_V_1_reg_1093 : STD_LOGIC_VECTOR (9 downto 0);
    signal y_V_2_fu_606_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal y_V_2_reg_1098 : STD_LOGIC_VECTOR (9 downto 0);
    signal y_V_3_fu_640_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal y_V_3_reg_1103 : STD_LOGIC_VECTOR (9 downto 0);
    signal y_V_4_fu_674_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal y_V_4_reg_1108 : STD_LOGIC_VECTOR (9 downto 0);
    signal y_V_4_reg_1108_pp0_iter1_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal exp_res_0_V_reg_1133 : STD_LOGIC_VECTOR (16 downto 0);
    signal exp_res_0_V_reg_1133_pp0_iter3_reg : STD_LOGIC_VECTOR (16 downto 0);
    signal exp_res_1_V_reg_1138 : STD_LOGIC_VECTOR (16 downto 0);
    signal exp_res_1_V_reg_1138_pp0_iter3_reg : STD_LOGIC_VECTOR (16 downto 0);
    signal exp_res_2_V_reg_1143 : STD_LOGIC_VECTOR (16 downto 0);
    signal exp_res_2_V_reg_1143_pp0_iter3_reg : STD_LOGIC_VECTOR (16 downto 0);
    signal exp_res_3_V_reg_1148 : STD_LOGIC_VECTOR (16 downto 0);
    signal exp_res_3_V_reg_1148_pp0_iter3_reg : STD_LOGIC_VECTOR (16 downto 0);
    signal p_Val2_16_fu_844_p3 : STD_LOGIC_VECTOR (17 downto 0);
    signal p_Val2_16_reg_1158 : STD_LOGIC_VECTOR (17 downto 0);
    signal exp_res_4_V_reg_1164 : STD_LOGIC_VECTOR (16 downto 0);
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal zext_ln255_fu_682_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln255_1_fu_686_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln255_2_fu_690_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln255_3_fu_694_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln255_4_fu_698_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln265_fu_954_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal icmp_ln1496_fu_172_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln1496_fu_172_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln1496_fu_172_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln65_fu_178_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln65_fu_178_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln1496_1_fu_186_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln1496_1_fu_186_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln1496_1_fu_186_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln65_1_fu_192_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln65_1_fu_192_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln65_fu_178_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln65_1_fu_192_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln1496_2_fu_200_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln65_2_fu_206_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln1496_3_fu_214_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln1496_3_fu_214_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal x_max_V_fu_220_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln703_fu_228_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal x_max_V_fu_220_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln703_fu_228_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal sext_ln703_1_fu_232_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal sub_ln1193_fu_236_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal tmp_3_fu_250_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_1_fu_242_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln786_fu_258_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln340_fu_276_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sext_ln703_2_fu_288_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln703_2_fu_288_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal sub_ln1193_1_fu_292_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal tmp_7_fu_306_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_5_fu_298_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln786_1_fu_314_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln340_1_fu_332_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sext_ln703_3_fu_344_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln703_3_fu_344_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal sub_ln1193_2_fu_348_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal tmp_10_fu_362_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_9_fu_354_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln786_2_fu_370_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln340_2_fu_388_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sext_ln703_4_fu_400_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln703_4_fu_400_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal sub_ln1193_3_fu_404_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal tmp_12_fu_418_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_11_fu_410_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln786_3_fu_426_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln340_3_fu_444_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sext_ln703_5_fu_456_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln703_5_fu_456_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal sub_ln1193_4_fu_460_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal tmp_14_fu_474_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_13_fu_466_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln786_4_fu_482_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln340_4_fu_500_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln340_5_fu_270_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_fu_512_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal and_ln786_fu_264_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln340_fu_282_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln340_fu_522_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal select_ln388_fu_530_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal xor_ln340_6_fu_326_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_2_fu_546_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal and_ln786_1_fu_320_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln340_1_fu_338_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln340_2_fu_556_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal select_ln388_1_fu_564_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal xor_ln340_7_fu_382_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_4_fu_580_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal and_ln786_2_fu_376_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln340_2_fu_394_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln340_4_fu_590_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal select_ln388_2_fu_598_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal xor_ln340_8_fu_438_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_6_fu_614_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal and_ln786_3_fu_432_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln340_3_fu_450_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln340_6_fu_624_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal select_ln388_3_fu_632_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal xor_ln340_9_fu_494_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_8_fu_648_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal and_ln786_4_fu_488_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln340_4_fu_506_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln340_8_fu_658_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal select_ln388_4_fu_666_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal p_Val2_6_fu_702_p1 : STD_LOGIC_VECTOR (17 downto 0);
    signal p_Val2_7_fu_706_p1 : STD_LOGIC_VECTOR (17 downto 0);
    signal p_Val2_8_fu_710_p2 : STD_LOGIC_VECTOR (17 downto 0);
    signal p_Result_s_fu_716_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Val2_9_fu_732_p1 : STD_LOGIC_VECTOR (17 downto 0);
    signal p_Val2_10_fu_736_p1 : STD_LOGIC_VECTOR (17 downto 0);
    signal p_Val2_11_fu_740_p2 : STD_LOGIC_VECTOR (17 downto 0);
    signal p_Result_14_fu_746_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Val2_12_fu_724_p3 : STD_LOGIC_VECTOR (17 downto 0);
    signal p_Val2_13_fu_754_p3 : STD_LOGIC_VECTOR (17 downto 0);
    signal rhs_V_fu_766_p1 : STD_LOGIC_VECTOR (18 downto 0);
    signal lhs_V_fu_762_p1 : STD_LOGIC_VECTOR (18 downto 0);
    signal ret_V_fu_770_p2 : STD_LOGIC_VECTOR (18 downto 0);
    signal p_Val2_15_fu_784_p2 : STD_LOGIC_VECTOR (17 downto 0);
    signal p_Result_16_fu_790_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_15_fu_776_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln786_5_fu_798_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln340_11_fu_816_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln340_10_fu_810_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal underflow_fu_804_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln340_5_fu_822_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln340_12_fu_828_p3 : STD_LOGIC_VECTOR (17 downto 0);
    signal select_ln388_5_fu_836_p3 : STD_LOGIC_VECTOR (17 downto 0);
    signal lhs_V_1_fu_856_p1 : STD_LOGIC_VECTOR (18 downto 0);
    signal rhs_V_1_fu_859_p1 : STD_LOGIC_VECTOR (18 downto 0);
    signal ret_V_1_fu_863_p2 : STD_LOGIC_VECTOR (18 downto 0);
    signal p_Val2_17_fu_852_p1 : STD_LOGIC_VECTOR (17 downto 0);
    signal p_Val2_19_fu_877_p2 : STD_LOGIC_VECTOR (17 downto 0);
    signal p_Result_18_fu_882_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_17_fu_869_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln786_6_fu_890_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln340_13_fu_908_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln340_12_fu_902_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_s_fu_920_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal underflow_1_fu_896_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln340_6_fu_914_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln340_14_fu_930_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal select_ln388_6_fu_938_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal y_V_5_fu_946_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal mul_ln1118_fu_1053_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal mul_ln1118_1_fu_1060_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal mul_ln1118_2_fu_1067_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal mul_ln1118_3_fu_1074_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal mul_ln1118_4_fu_1081_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal mul_ln1118_fu_1053_p0 : STD_LOGIC_VECTOR (17 downto 0);
    signal sext_ln1116_fu_959_p1 : STD_LOGIC_VECTOR (25 downto 0);
    signal mul_ln1118_fu_1053_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal mul_ln1118_1_fu_1060_p0 : STD_LOGIC_VECTOR (17 downto 0);
    signal mul_ln1118_1_fu_1060_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal mul_ln1118_2_fu_1067_p0 : STD_LOGIC_VECTOR (17 downto 0);
    signal mul_ln1118_2_fu_1067_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal mul_ln1118_3_fu_1074_p0 : STD_LOGIC_VECTOR (17 downto 0);
    signal mul_ln1118_3_fu_1074_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal mul_ln1118_4_fu_1081_p0 : STD_LOGIC_VECTOR (17 downto 0);
    signal mul_ln1118_4_fu_1081_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_idle_pp0_0to3 : STD_LOGIC;
    signal ap_reset_idle_pp0 : STD_LOGIC;
    signal ap_enable_pp0 : STD_LOGIC;
    signal mul_ln1118_1_fu_1060_p10 : STD_LOGIC_VECTOR (25 downto 0);
    signal mul_ln1118_2_fu_1067_p10 : STD_LOGIC_VECTOR (25 downto 0);
    signal mul_ln1118_3_fu_1074_p10 : STD_LOGIC_VECTOR (25 downto 0);
    signal mul_ln1118_4_fu_1081_p10 : STD_LOGIC_VECTOR (25 downto 0);
    signal mul_ln1118_fu_1053_p10 : STD_LOGIC_VECTOR (25 downto 0);

    component myproject_mul_mul_18s_17ns_26_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (17 downto 0);
        din1 : IN STD_LOGIC_VECTOR (16 downto 0);
        dout : OUT STD_LOGIC_VECTOR (25 downto 0) );
    end component;


    component softmax_stable_ap_fixed_ap_fixed_16_6_5_3_0_softmax_config13_s_exp_table1 IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (9 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (16 downto 0);
        address1 : IN STD_LOGIC_VECTOR (9 downto 0);
        ce1 : IN STD_LOGIC;
        q1 : OUT STD_LOGIC_VECTOR (16 downto 0);
        address2 : IN STD_LOGIC_VECTOR (9 downto 0);
        ce2 : IN STD_LOGIC;
        q2 : OUT STD_LOGIC_VECTOR (16 downto 0);
        address3 : IN STD_LOGIC_VECTOR (9 downto 0);
        ce3 : IN STD_LOGIC;
        q3 : OUT STD_LOGIC_VECTOR (16 downto 0);
        address4 : IN STD_LOGIC_VECTOR (9 downto 0);
        ce4 : IN STD_LOGIC;
        q4 : OUT STD_LOGIC_VECTOR (16 downto 0) );
    end component;


    component softmax_stable_ap_fixed_ap_fixed_16_6_5_3_0_softmax_config13_s_invert_table2 IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (9 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (17 downto 0) );
    end component;



begin
    exp_table1_U : component softmax_stable_ap_fixed_ap_fixed_16_6_5_3_0_softmax_config13_s_exp_table1
    generic map (
        DataWidth => 17,
        AddressRange => 1024,
        AddressWidth => 10)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => exp_table1_address0,
        ce0 => exp_table1_ce0,
        q0 => exp_table1_q0,
        address1 => exp_table1_address1,
        ce1 => exp_table1_ce1,
        q1 => exp_table1_q1,
        address2 => exp_table1_address2,
        ce2 => exp_table1_ce2,
        q2 => exp_table1_q2,
        address3 => exp_table1_address3,
        ce3 => exp_table1_ce3,
        q3 => exp_table1_q3,
        address4 => exp_table1_address4,
        ce4 => exp_table1_ce4,
        q4 => exp_table1_q4);

    invert_table2_U : component softmax_stable_ap_fixed_ap_fixed_16_6_5_3_0_softmax_config13_s_invert_table2
    generic map (
        DataWidth => 18,
        AddressRange => 1024,
        AddressWidth => 10)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => invert_table2_address0,
        ce0 => invert_table2_ce0,
        q0 => invert_table2_q0);

    myproject_mul_mul_18s_17ns_26_1_1_U258 : component myproject_mul_mul_18s_17ns_26_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 18,
        din1_WIDTH => 17,
        dout_WIDTH => 26)
    port map (
        din0 => mul_ln1118_fu_1053_p0,
        din1 => mul_ln1118_fu_1053_p1,
        dout => mul_ln1118_fu_1053_p2);

    myproject_mul_mul_18s_17ns_26_1_1_U259 : component myproject_mul_mul_18s_17ns_26_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 18,
        din1_WIDTH => 17,
        dout_WIDTH => 26)
    port map (
        din0 => mul_ln1118_1_fu_1060_p0,
        din1 => mul_ln1118_1_fu_1060_p1,
        dout => mul_ln1118_1_fu_1060_p2);

    myproject_mul_mul_18s_17ns_26_1_1_U260 : component myproject_mul_mul_18s_17ns_26_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 18,
        din1_WIDTH => 17,
        dout_WIDTH => 26)
    port map (
        din0 => mul_ln1118_2_fu_1067_p0,
        din1 => mul_ln1118_2_fu_1067_p1,
        dout => mul_ln1118_2_fu_1067_p2);

    myproject_mul_mul_18s_17ns_26_1_1_U261 : component myproject_mul_mul_18s_17ns_26_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 18,
        din1_WIDTH => 17,
        dout_WIDTH => 26)
    port map (
        din0 => mul_ln1118_3_fu_1074_p0,
        din1 => mul_ln1118_3_fu_1074_p1,
        dout => mul_ln1118_3_fu_1074_p2);

    myproject_mul_mul_18s_17ns_26_1_1_U262 : component myproject_mul_mul_18s_17ns_26_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 18,
        din1_WIDTH => 17,
        dout_WIDTH => 26)
    port map (
        din0 => mul_ln1118_4_fu_1081_p0,
        din1 => mul_ln1118_4_fu_1081_p1,
        dout => mul_ln1118_4_fu_1081_p2);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_ce) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then
                exp_res_0_V_reg_1133 <= exp_table1_q0;
                exp_res_1_V_reg_1138 <= exp_table1_q1;
                exp_res_2_V_reg_1143 <= exp_table1_q2;
                exp_res_3_V_reg_1148 <= exp_table1_q3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_ce) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                exp_res_0_V_reg_1133_pp0_iter3_reg <= exp_res_0_V_reg_1133;
                exp_res_1_V_reg_1138_pp0_iter3_reg <= exp_res_1_V_reg_1138;
                exp_res_2_V_reg_1143_pp0_iter3_reg <= exp_res_2_V_reg_1143;
                exp_res_3_V_reg_1148_pp0_iter3_reg <= exp_res_3_V_reg_1148;
                p_Val2_16_reg_1158 <= p_Val2_16_fu_844_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_ce) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then
                exp_res_4_V_reg_1164 <= exp_table1_q4;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_ce) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                y_V_1_reg_1093 <= y_V_1_fu_572_p3;
                y_V_2_reg_1098 <= y_V_2_fu_606_p3;
                y_V_3_reg_1103 <= y_V_3_fu_640_p3;
                y_V_4_reg_1108 <= y_V_4_fu_674_p3;
                y_V_4_reg_1108_pp0_iter1_reg <= y_V_4_reg_1108;
                y_V_reg_1088 <= y_V_fu_538_p3;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_block_pp0_stage0_subdone, ap_reset_idle_pp0)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    and_ln786_1_fu_320_p2 <= (xor_ln786_1_fu_314_p2 and tmp_5_fu_298_p3);
    and_ln786_2_fu_376_p2 <= (xor_ln786_2_fu_370_p2 and tmp_9_fu_354_p3);
    and_ln786_3_fu_432_p2 <= (xor_ln786_3_fu_426_p2 and tmp_11_fu_410_p3);
    and_ln786_4_fu_488_p2 <= (xor_ln786_4_fu_482_p2 and tmp_13_fu_466_p3);
    and_ln786_fu_264_p2 <= (xor_ln786_fu_258_p2 and tmp_1_fu_242_p3);
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_11001_assign_proc : process(ap_start)
    begin
                ap_block_pp0_stage0_11001 <= ((ap_start = ap_const_logic_0) and (ap_start = ap_const_logic_1));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(ap_start, ap_ce)
    begin
                ap_block_pp0_stage0_subdone <= ((ap_const_logic_0 = ap_ce) or ((ap_start = ap_const_logic_0) and (ap_start = ap_const_logic_1)));
    end process;


    ap_block_state1_pp0_stage0_iter0_assign_proc : process(ap_start)
    begin
                ap_block_state1_pp0_stage0_iter0 <= (ap_start = ap_const_logic_0);
    end process;

        ap_block_state2_pp0_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state3_pp0_stage0_iter2 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state4_pp0_stage0_iter3 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state5_pp0_stage0_iter4 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_done_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_enable_reg_pp0_iter4, ap_block_pp0_stage0_11001, ap_ce)
    begin
        if ((((ap_start = ap_const_logic_0) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((ap_const_logic_1 = ap_ce) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1)))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start;

    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_idle_pp0)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4)
    begin
        if (((ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_0to3_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3)
    begin
        if (((ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0_0to3 <= ap_const_logic_1;
        else 
            ap_idle_pp0_0to3 <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, ap_ce)
    begin
        if (((ap_const_logic_1 = ap_ce) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    ap_reset_idle_pp0_assign_proc : process(ap_start, ap_idle_pp0_0to3)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_idle_pp0_0to3 = ap_const_logic_1))) then 
            ap_reset_idle_pp0 <= ap_const_logic_1;
        else 
            ap_reset_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_return_0 <= mul_ln1118_fu_1053_p2(25 downto 10);
    ap_return_1 <= mul_ln1118_1_fu_1060_p2(25 downto 10);
    ap_return_2 <= mul_ln1118_2_fu_1067_p2(25 downto 10);
    ap_return_3 <= mul_ln1118_3_fu_1074_p2(25 downto 10);
    ap_return_4 <= mul_ln1118_4_fu_1081_p2(25 downto 10);
    exp_table1_address0 <= zext_ln255_fu_682_p1(10 - 1 downto 0);
    exp_table1_address1 <= zext_ln255_1_fu_686_p1(10 - 1 downto 0);
    exp_table1_address2 <= zext_ln255_2_fu_690_p1(10 - 1 downto 0);
    exp_table1_address3 <= zext_ln255_3_fu_694_p1(10 - 1 downto 0);
    exp_table1_address4 <= zext_ln255_4_fu_698_p1(10 - 1 downto 0);

    exp_table1_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001, ap_ce)
    begin
        if (((ap_const_logic_1 = ap_ce) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            exp_table1_ce0 <= ap_const_logic_1;
        else 
            exp_table1_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    exp_table1_ce1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001, ap_ce)
    begin
        if (((ap_const_logic_1 = ap_ce) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            exp_table1_ce1 <= ap_const_logic_1;
        else 
            exp_table1_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    exp_table1_ce2_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001, ap_ce)
    begin
        if (((ap_const_logic_1 = ap_ce) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            exp_table1_ce2 <= ap_const_logic_1;
        else 
            exp_table1_ce2 <= ap_const_logic_0;
        end if; 
    end process;


    exp_table1_ce3_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001, ap_ce)
    begin
        if (((ap_const_logic_1 = ap_ce) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            exp_table1_ce3 <= ap_const_logic_1;
        else 
            exp_table1_ce3 <= ap_const_logic_0;
        end if; 
    end process;


    exp_table1_ce4_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, ap_ce)
    begin
        if (((ap_const_logic_1 = ap_ce) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            exp_table1_ce4 <= ap_const_logic_1;
        else 
            exp_table1_ce4 <= ap_const_logic_0;
        end if; 
    end process;

    icmp_ln1496_1_fu_186_p0 <= data_2_V_read;
    icmp_ln1496_1_fu_186_p1 <= data_3_V_read;
    icmp_ln1496_1_fu_186_p2 <= "1" when (signed(icmp_ln1496_1_fu_186_p0) < signed(icmp_ln1496_1_fu_186_p1)) else "0";
    icmp_ln1496_2_fu_200_p2 <= "1" when (signed(select_ln65_fu_178_p3) < signed(select_ln65_1_fu_192_p3)) else "0";
    icmp_ln1496_3_fu_214_p1 <= data_4_V_read;
    icmp_ln1496_3_fu_214_p2 <= "1" when (signed(select_ln65_2_fu_206_p3) < signed(icmp_ln1496_3_fu_214_p1)) else "0";
    icmp_ln1496_fu_172_p0 <= data_0_V_read;
    icmp_ln1496_fu_172_p1 <= data_1_V_read;
    icmp_ln1496_fu_172_p2 <= "1" when (signed(icmp_ln1496_fu_172_p0) < signed(icmp_ln1496_fu_172_p1)) else "0";
    invert_table2_address0 <= zext_ln265_fu_954_p1(10 - 1 downto 0);

    invert_table2_ce0_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_11001, ap_ce)
    begin
        if (((ap_const_logic_1 = ap_ce) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            invert_table2_ce0 <= ap_const_logic_1;
        else 
            invert_table2_ce0 <= ap_const_logic_0;
        end if; 
    end process;

        lhs_V_1_fu_856_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(p_Val2_16_reg_1158),19));

        lhs_V_fu_762_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(p_Val2_12_fu_724_p3),19));

    mul_ln1118_1_fu_1060_p0 <= sext_ln1116_fu_959_p1(18 - 1 downto 0);
    mul_ln1118_1_fu_1060_p1 <= mul_ln1118_1_fu_1060_p10(17 - 1 downto 0);
    mul_ln1118_1_fu_1060_p10 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(exp_res_1_V_reg_1138_pp0_iter3_reg),26));
    mul_ln1118_2_fu_1067_p0 <= sext_ln1116_fu_959_p1(18 - 1 downto 0);
    mul_ln1118_2_fu_1067_p1 <= mul_ln1118_2_fu_1067_p10(17 - 1 downto 0);
    mul_ln1118_2_fu_1067_p10 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(exp_res_2_V_reg_1143_pp0_iter3_reg),26));
    mul_ln1118_3_fu_1074_p0 <= sext_ln1116_fu_959_p1(18 - 1 downto 0);
    mul_ln1118_3_fu_1074_p1 <= mul_ln1118_3_fu_1074_p10(17 - 1 downto 0);
    mul_ln1118_3_fu_1074_p10 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(exp_res_3_V_reg_1148_pp0_iter3_reg),26));
    mul_ln1118_4_fu_1081_p0 <= sext_ln1116_fu_959_p1(18 - 1 downto 0);
    mul_ln1118_4_fu_1081_p1 <= mul_ln1118_4_fu_1081_p10(17 - 1 downto 0);
    mul_ln1118_4_fu_1081_p10 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(exp_res_4_V_reg_1164),26));
    mul_ln1118_fu_1053_p0 <= sext_ln1116_fu_959_p1(18 - 1 downto 0);
    mul_ln1118_fu_1053_p1 <= mul_ln1118_fu_1053_p10(17 - 1 downto 0);
    mul_ln1118_fu_1053_p10 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(exp_res_0_V_reg_1133_pp0_iter3_reg),26));
    or_ln340_1_fu_338_p2 <= (xor_ln340_1_fu_332_p2 or tmp_7_fu_306_p3);
    or_ln340_2_fu_394_p2 <= (xor_ln340_2_fu_388_p2 or tmp_10_fu_362_p3);
    or_ln340_3_fu_450_p2 <= (xor_ln340_3_fu_444_p2 or tmp_12_fu_418_p3);
    or_ln340_4_fu_506_p2 <= (xor_ln340_4_fu_500_p2 or tmp_14_fu_474_p3);
    or_ln340_5_fu_822_p2 <= (xor_ln340_11_fu_816_p2 or p_Result_16_fu_790_p3);
    or_ln340_6_fu_914_p2 <= (xor_ln340_13_fu_908_p2 or p_Result_18_fu_882_p3);
    or_ln340_fu_282_p2 <= (xor_ln340_fu_276_p2 or tmp_3_fu_250_p3);
    p_Result_14_fu_746_p3 <= p_Val2_11_fu_740_p2(17 downto 17);
    p_Result_15_fu_776_p3 <= ret_V_fu_770_p2(18 downto 18);
    p_Result_16_fu_790_p3 <= p_Val2_15_fu_784_p2(17 downto 17);
    p_Result_17_fu_869_p3 <= ret_V_1_fu_863_p2(18 downto 18);
    p_Result_18_fu_882_p3 <= p_Val2_19_fu_877_p2(17 downto 17);
    p_Result_s_fu_716_p3 <= p_Val2_8_fu_710_p2(17 downto 17);
    p_Val2_10_fu_736_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(exp_table1_q3),18));
    p_Val2_11_fu_740_p2 <= std_logic_vector(unsigned(p_Val2_9_fu_732_p1) + unsigned(p_Val2_10_fu_736_p1));
    p_Val2_12_fu_724_p3 <= 
        ap_const_lv18_1FFFF when (p_Result_s_fu_716_p3(0) = '1') else 
        p_Val2_8_fu_710_p2;
    p_Val2_13_fu_754_p3 <= 
        ap_const_lv18_1FFFF when (p_Result_14_fu_746_p3(0) = '1') else 
        p_Val2_11_fu_740_p2;
    p_Val2_15_fu_784_p2 <= std_logic_vector(signed(p_Val2_12_fu_724_p3) + signed(p_Val2_13_fu_754_p3));
    p_Val2_16_fu_844_p3 <= 
        select_ln340_12_fu_828_p3 when (or_ln340_5_fu_822_p2(0) = '1') else 
        select_ln388_5_fu_836_p3;
    p_Val2_17_fu_852_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(exp_table1_q4),18));
    p_Val2_19_fu_877_p2 <= std_logic_vector(unsigned(p_Val2_17_fu_852_p1) + unsigned(p_Val2_16_reg_1158));
    p_Val2_6_fu_702_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(exp_table1_q0),18));
    p_Val2_7_fu_706_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(exp_table1_q1),18));
    p_Val2_8_fu_710_p2 <= std_logic_vector(unsigned(p_Val2_6_fu_702_p1) + unsigned(p_Val2_7_fu_706_p1));
    p_Val2_9_fu_732_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(exp_table1_q2),18));
    ret_V_1_fu_863_p2 <= std_logic_vector(signed(lhs_V_1_fu_856_p1) + signed(rhs_V_1_fu_859_p1));
    ret_V_fu_770_p2 <= std_logic_vector(signed(rhs_V_fu_766_p1) + signed(lhs_V_fu_762_p1));
    rhs_V_1_fu_859_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(exp_table1_q4),19));
        rhs_V_fu_766_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(p_Val2_13_fu_754_p3),19));

    select_ln340_12_fu_828_p3 <= 
        ap_const_lv18_1FFFF when (xor_ln340_10_fu_810_p2(0) = '1') else 
        p_Val2_15_fu_784_p2;
    select_ln340_14_fu_930_p3 <= 
        ap_const_lv10_1FF when (xor_ln340_12_fu_902_p2(0) = '1') else 
        tmp_s_fu_920_p4;
    select_ln340_2_fu_556_p3 <= 
        ap_const_lv10_1FF when (xor_ln340_6_fu_326_p2(0) = '1') else 
        tmp_2_fu_546_p4;
    select_ln340_4_fu_590_p3 <= 
        ap_const_lv10_1FF when (xor_ln340_7_fu_382_p2(0) = '1') else 
        tmp_4_fu_580_p4;
    select_ln340_6_fu_624_p3 <= 
        ap_const_lv10_1FF when (xor_ln340_8_fu_438_p2(0) = '1') else 
        tmp_6_fu_614_p4;
    select_ln340_8_fu_658_p3 <= 
        ap_const_lv10_1FF when (xor_ln340_9_fu_494_p2(0) = '1') else 
        tmp_8_fu_648_p4;
    select_ln340_fu_522_p3 <= 
        ap_const_lv10_1FF when (xor_ln340_5_fu_270_p2(0) = '1') else 
        tmp_fu_512_p4;
    select_ln388_1_fu_564_p3 <= 
        ap_const_lv10_200 when (and_ln786_1_fu_320_p2(0) = '1') else 
        tmp_2_fu_546_p4;
    select_ln388_2_fu_598_p3 <= 
        ap_const_lv10_200 when (and_ln786_2_fu_376_p2(0) = '1') else 
        tmp_4_fu_580_p4;
    select_ln388_3_fu_632_p3 <= 
        ap_const_lv10_200 when (and_ln786_3_fu_432_p2(0) = '1') else 
        tmp_6_fu_614_p4;
    select_ln388_4_fu_666_p3 <= 
        ap_const_lv10_200 when (and_ln786_4_fu_488_p2(0) = '1') else 
        tmp_8_fu_648_p4;
    select_ln388_5_fu_836_p3 <= 
        ap_const_lv18_20000 when (underflow_fu_804_p2(0) = '1') else 
        p_Val2_15_fu_784_p2;
    select_ln388_6_fu_938_p3 <= 
        ap_const_lv10_200 when (underflow_1_fu_896_p2(0) = '1') else 
        tmp_s_fu_920_p4;
    select_ln388_fu_530_p3 <= 
        ap_const_lv10_200 when (and_ln786_fu_264_p2(0) = '1') else 
        tmp_fu_512_p4;
    select_ln65_1_fu_192_p1 <= data_3_V_read;
    select_ln65_1_fu_192_p2 <= data_2_V_read;
    select_ln65_1_fu_192_p3 <= 
        select_ln65_1_fu_192_p1 when (icmp_ln1496_1_fu_186_p2(0) = '1') else 
        select_ln65_1_fu_192_p2;
    select_ln65_2_fu_206_p3 <= 
        select_ln65_1_fu_192_p3 when (icmp_ln1496_2_fu_200_p2(0) = '1') else 
        select_ln65_fu_178_p3;
    select_ln65_fu_178_p1 <= data_1_V_read;
    select_ln65_fu_178_p2 <= data_0_V_read;
    select_ln65_fu_178_p3 <= 
        select_ln65_fu_178_p1 when (icmp_ln1496_fu_172_p2(0) = '1') else 
        select_ln65_fu_178_p2;
        sext_ln1116_fu_959_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(invert_table2_q0),26));

        sext_ln703_1_fu_232_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(x_max_V_fu_220_p3),17));

    sext_ln703_2_fu_288_p0 <= data_1_V_read;
        sext_ln703_2_fu_288_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln703_2_fu_288_p0),17));

    sext_ln703_3_fu_344_p0 <= data_2_V_read;
        sext_ln703_3_fu_344_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln703_3_fu_344_p0),17));

    sext_ln703_4_fu_400_p0 <= data_3_V_read;
        sext_ln703_4_fu_400_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln703_4_fu_400_p0),17));

    sext_ln703_5_fu_456_p0 <= data_4_V_read;
        sext_ln703_5_fu_456_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln703_5_fu_456_p0),17));

    sext_ln703_fu_228_p0 <= data_0_V_read;
        sext_ln703_fu_228_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln703_fu_228_p0),17));

    sub_ln1193_1_fu_292_p2 <= std_logic_vector(signed(sext_ln703_2_fu_288_p1) - signed(sext_ln703_1_fu_232_p1));
    sub_ln1193_2_fu_348_p2 <= std_logic_vector(signed(sext_ln703_3_fu_344_p1) - signed(sext_ln703_1_fu_232_p1));
    sub_ln1193_3_fu_404_p2 <= std_logic_vector(signed(sext_ln703_4_fu_400_p1) - signed(sext_ln703_1_fu_232_p1));
    sub_ln1193_4_fu_460_p2 <= std_logic_vector(signed(sext_ln703_5_fu_456_p1) - signed(sext_ln703_1_fu_232_p1));
    sub_ln1193_fu_236_p2 <= std_logic_vector(signed(sext_ln703_fu_228_p1) - signed(sext_ln703_1_fu_232_p1));
    tmp_10_fu_362_p3 <= sub_ln1193_2_fu_348_p2(15 downto 15);
    tmp_11_fu_410_p3 <= sub_ln1193_3_fu_404_p2(16 downto 16);
    tmp_12_fu_418_p3 <= sub_ln1193_3_fu_404_p2(15 downto 15);
    tmp_13_fu_466_p3 <= sub_ln1193_4_fu_460_p2(16 downto 16);
    tmp_14_fu_474_p3 <= sub_ln1193_4_fu_460_p2(15 downto 15);
    tmp_1_fu_242_p3 <= sub_ln1193_fu_236_p2(16 downto 16);
    tmp_2_fu_546_p4 <= sub_ln1193_1_fu_292_p2(15 downto 6);
    tmp_3_fu_250_p3 <= sub_ln1193_fu_236_p2(15 downto 15);
    tmp_4_fu_580_p4 <= sub_ln1193_2_fu_348_p2(15 downto 6);
    tmp_5_fu_298_p3 <= sub_ln1193_1_fu_292_p2(16 downto 16);
    tmp_6_fu_614_p4 <= sub_ln1193_3_fu_404_p2(15 downto 6);
    tmp_7_fu_306_p3 <= sub_ln1193_1_fu_292_p2(15 downto 15);
    tmp_8_fu_648_p4 <= sub_ln1193_4_fu_460_p2(15 downto 6);
    tmp_9_fu_354_p3 <= sub_ln1193_2_fu_348_p2(16 downto 16);
    tmp_fu_512_p4 <= sub_ln1193_fu_236_p2(15 downto 6);
    tmp_s_fu_920_p4 <= p_Val2_19_fu_877_p2(17 downto 8);
    underflow_1_fu_896_p2 <= (xor_ln786_6_fu_890_p2 and p_Result_17_fu_869_p3);
    underflow_fu_804_p2 <= (xor_ln786_5_fu_798_p2 and p_Result_15_fu_776_p3);
    x_max_V_fu_220_p1 <= data_4_V_read;
    x_max_V_fu_220_p3 <= 
        x_max_V_fu_220_p1 when (icmp_ln1496_3_fu_214_p2(0) = '1') else 
        select_ln65_2_fu_206_p3;
    xor_ln340_10_fu_810_p2 <= (p_Result_16_fu_790_p3 xor p_Result_15_fu_776_p3);
    xor_ln340_11_fu_816_p2 <= (p_Result_15_fu_776_p3 xor ap_const_lv1_1);
    xor_ln340_12_fu_902_p2 <= (p_Result_18_fu_882_p3 xor p_Result_17_fu_869_p3);
    xor_ln340_13_fu_908_p2 <= (p_Result_17_fu_869_p3 xor ap_const_lv1_1);
    xor_ln340_1_fu_332_p2 <= (tmp_5_fu_298_p3 xor ap_const_lv1_1);
    xor_ln340_2_fu_388_p2 <= (tmp_9_fu_354_p3 xor ap_const_lv1_1);
    xor_ln340_3_fu_444_p2 <= (tmp_11_fu_410_p3 xor ap_const_lv1_1);
    xor_ln340_4_fu_500_p2 <= (tmp_13_fu_466_p3 xor ap_const_lv1_1);
    xor_ln340_5_fu_270_p2 <= (tmp_3_fu_250_p3 xor tmp_1_fu_242_p3);
    xor_ln340_6_fu_326_p2 <= (tmp_7_fu_306_p3 xor tmp_5_fu_298_p3);
    xor_ln340_7_fu_382_p2 <= (tmp_9_fu_354_p3 xor tmp_10_fu_362_p3);
    xor_ln340_8_fu_438_p2 <= (tmp_12_fu_418_p3 xor tmp_11_fu_410_p3);
    xor_ln340_9_fu_494_p2 <= (tmp_14_fu_474_p3 xor tmp_13_fu_466_p3);
    xor_ln340_fu_276_p2 <= (tmp_1_fu_242_p3 xor ap_const_lv1_1);
    xor_ln786_1_fu_314_p2 <= (tmp_7_fu_306_p3 xor ap_const_lv1_1);
    xor_ln786_2_fu_370_p2 <= (tmp_10_fu_362_p3 xor ap_const_lv1_1);
    xor_ln786_3_fu_426_p2 <= (tmp_12_fu_418_p3 xor ap_const_lv1_1);
    xor_ln786_4_fu_482_p2 <= (tmp_14_fu_474_p3 xor ap_const_lv1_1);
    xor_ln786_5_fu_798_p2 <= (p_Result_16_fu_790_p3 xor ap_const_lv1_1);
    xor_ln786_6_fu_890_p2 <= (p_Result_18_fu_882_p3 xor ap_const_lv1_1);
    xor_ln786_fu_258_p2 <= (tmp_3_fu_250_p3 xor ap_const_lv1_1);
    y_V_1_fu_572_p3 <= 
        select_ln340_2_fu_556_p3 when (or_ln340_1_fu_338_p2(0) = '1') else 
        select_ln388_1_fu_564_p3;
    y_V_2_fu_606_p3 <= 
        select_ln340_4_fu_590_p3 when (or_ln340_2_fu_394_p2(0) = '1') else 
        select_ln388_2_fu_598_p3;
    y_V_3_fu_640_p3 <= 
        select_ln340_6_fu_624_p3 when (or_ln340_3_fu_450_p2(0) = '1') else 
        select_ln388_3_fu_632_p3;
    y_V_4_fu_674_p3 <= 
        select_ln340_8_fu_658_p3 when (or_ln340_4_fu_506_p2(0) = '1') else 
        select_ln388_4_fu_666_p3;
    y_V_5_fu_946_p3 <= 
        select_ln340_14_fu_930_p3 when (or_ln340_6_fu_914_p2(0) = '1') else 
        select_ln388_6_fu_938_p3;
    y_V_fu_538_p3 <= 
        select_ln340_fu_522_p3 when (or_ln340_fu_282_p2(0) = '1') else 
        select_ln388_fu_530_p3;
    zext_ln255_1_fu_686_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(y_V_1_reg_1093),64));
    zext_ln255_2_fu_690_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(y_V_2_reg_1098),64));
    zext_ln255_3_fu_694_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(y_V_3_reg_1103),64));
    zext_ln255_4_fu_698_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(y_V_4_reg_1108_pp0_iter1_reg),64));
    zext_ln255_fu_682_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(y_V_reg_1088),64));
    zext_ln265_fu_954_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(y_V_5_fu_946_p3),64));
end behav;
