// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "softmax_stable_ap_fixed_ap_fixed_16_6_5_3_0_softmax_config13_s.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic softmax_stable_ap_fixed_ap_fixed_16_6_5_3_0_softmax_config13_s::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic softmax_stable_ap_fixed_ap_fixed_16_6_5_3_0_softmax_config13_s::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<1> softmax_stable_ap_fixed_ap_fixed_16_6_5_3_0_softmax_config13_s::ap_ST_fsm_pp0_stage0 = "1";
const bool softmax_stable_ap_fixed_ap_fixed_16_6_5_3_0_softmax_config13_s::ap_const_boolean_1 = true;
const sc_lv<32> softmax_stable_ap_fixed_ap_fixed_16_6_5_3_0_softmax_config13_s::ap_const_lv32_0 = "00000000000000000000000000000000";
const bool softmax_stable_ap_fixed_ap_fixed_16_6_5_3_0_softmax_config13_s::ap_const_boolean_0 = false;
const sc_lv<32> softmax_stable_ap_fixed_ap_fixed_16_6_5_3_0_softmax_config13_s::ap_const_lv32_10 = "10000";
const sc_lv<32> softmax_stable_ap_fixed_ap_fixed_16_6_5_3_0_softmax_config13_s::ap_const_lv32_F = "1111";
const sc_lv<1> softmax_stable_ap_fixed_ap_fixed_16_6_5_3_0_softmax_config13_s::ap_const_lv1_1 = "1";
const sc_lv<32> softmax_stable_ap_fixed_ap_fixed_16_6_5_3_0_softmax_config13_s::ap_const_lv32_6 = "110";
const sc_lv<10> softmax_stable_ap_fixed_ap_fixed_16_6_5_3_0_softmax_config13_s::ap_const_lv10_1FF = "111111111";
const sc_lv<10> softmax_stable_ap_fixed_ap_fixed_16_6_5_3_0_softmax_config13_s::ap_const_lv10_200 = "1000000000";
const sc_lv<32> softmax_stable_ap_fixed_ap_fixed_16_6_5_3_0_softmax_config13_s::ap_const_lv32_8 = "1000";
const sc_lv<32> softmax_stable_ap_fixed_ap_fixed_16_6_5_3_0_softmax_config13_s::ap_const_lv32_11 = "10001";
const sc_lv<32> softmax_stable_ap_fixed_ap_fixed_16_6_5_3_0_softmax_config13_s::ap_const_lv32_E = "1110";
const sc_lv<32> softmax_stable_ap_fixed_ap_fixed_16_6_5_3_0_softmax_config13_s::ap_const_lv32_1D = "11101";

softmax_stable_ap_fixed_ap_fixed_16_6_5_3_0_softmax_config13_s::softmax_stable_ap_fixed_ap_fixed_16_6_5_3_0_softmax_config13_s(sc_module_name name) : sc_module(name), mVcdFile(0) {
    exp_table1_U = new softmax_stable_ap_fixed_ap_fixed_16_6_5_3_0_softmax_config13_s_exp_table1("exp_table1_U");
    exp_table1_U->clk(ap_clk);
    exp_table1_U->reset(ap_rst);
    exp_table1_U->address0(exp_table1_address0);
    exp_table1_U->ce0(exp_table1_ce0);
    exp_table1_U->q0(exp_table1_q0);
    exp_table1_U->address1(exp_table1_address1);
    exp_table1_U->ce1(exp_table1_ce1);
    exp_table1_U->q1(exp_table1_q1);
    exp_table1_U->address2(exp_table1_address2);
    exp_table1_U->ce2(exp_table1_ce2);
    exp_table1_U->q2(exp_table1_q2);
    exp_table1_U->address3(exp_table1_address3);
    exp_table1_U->ce3(exp_table1_ce3);
    exp_table1_U->q3(exp_table1_q3);
    exp_table1_U->address4(exp_table1_address4);
    exp_table1_U->ce4(exp_table1_ce4);
    exp_table1_U->q4(exp_table1_q4);
    invert_table2_U = new softmax_stable_ap_fixed_ap_fixed_16_6_5_3_0_softmax_config13_s_invert_table2("invert_table2_U");
    invert_table2_U->clk(ap_clk);
    invert_table2_U->reset(ap_rst);
    invert_table2_U->address0(invert_table2_address0);
    invert_table2_U->ce0(invert_table2_ce0);
    invert_table2_U->q0(invert_table2_q0);
    myproject_mul_mul_18s_18s_30_1_1_U222 = new myproject_mul_mul_18s_18s_30_1_1<1,1,18,18,30>("myproject_mul_mul_18s_18s_30_1_1_U222");
    myproject_mul_mul_18s_18s_30_1_1_U222->din0(exp_res_0_V_reg_910);
    myproject_mul_mul_18s_18s_30_1_1_U222->din1(mul_ln1118_fu_825_p1);
    myproject_mul_mul_18s_18s_30_1_1_U222->dout(mul_ln1118_fu_825_p2);
    myproject_mul_mul_18s_18s_30_1_1_U223 = new myproject_mul_mul_18s_18s_30_1_1<1,1,18,18,30>("myproject_mul_mul_18s_18s_30_1_1_U223");
    myproject_mul_mul_18s_18s_30_1_1_U223->din0(exp_res_1_V_reg_915);
    myproject_mul_mul_18s_18s_30_1_1_U223->din1(mul_ln1118_1_fu_832_p1);
    myproject_mul_mul_18s_18s_30_1_1_U223->dout(mul_ln1118_1_fu_832_p2);
    myproject_mul_mul_18s_18s_30_1_1_U224 = new myproject_mul_mul_18s_18s_30_1_1<1,1,18,18,30>("myproject_mul_mul_18s_18s_30_1_1_U224");
    myproject_mul_mul_18s_18s_30_1_1_U224->din0(exp_res_2_V_reg_920);
    myproject_mul_mul_18s_18s_30_1_1_U224->din1(mul_ln1118_2_fu_839_p1);
    myproject_mul_mul_18s_18s_30_1_1_U224->dout(mul_ln1118_2_fu_839_p2);
    myproject_mul_mul_18s_18s_30_1_1_U225 = new myproject_mul_mul_18s_18s_30_1_1<1,1,18,18,30>("myproject_mul_mul_18s_18s_30_1_1_U225");
    myproject_mul_mul_18s_18s_30_1_1_U225->din0(exp_res_3_V_reg_925);
    myproject_mul_mul_18s_18s_30_1_1_U225->din1(mul_ln1118_3_fu_846_p1);
    myproject_mul_mul_18s_18s_30_1_1_U225->dout(mul_ln1118_3_fu_846_p2);
    myproject_mul_mul_18s_18s_30_1_1_U226 = new myproject_mul_mul_18s_18s_30_1_1<1,1,18,18,30>("myproject_mul_mul_18s_18s_30_1_1_U226");
    myproject_mul_mul_18s_18s_30_1_1_U226->din0(exp_res_4_V_reg_930);
    myproject_mul_mul_18s_18s_30_1_1_U226->din1(mul_ln1118_4_fu_853_p1);
    myproject_mul_mul_18s_18s_30_1_1_U226->dout(mul_ln1118_4_fu_853_p2);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_add_ln703_1_fu_698_p0);
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( exp_table1_q4 );

    SC_METHOD(thread_add_ln703_1_fu_698_p1);
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( exp_table1_q2 );

    SC_METHOD(thread_add_ln703_1_fu_698_p2);
    sensitive << ( add_ln703_1_fu_698_p0 );
    sensitive << ( add_ln703_1_fu_698_p1 );

    SC_METHOD(thread_add_ln703_2_fu_704_p0);
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( exp_table1_q3 );

    SC_METHOD(thread_add_ln703_2_fu_704_p2);
    sensitive << ( add_ln703_2_fu_704_p0 );
    sensitive << ( add_ln703_1_fu_698_p2 );

    SC_METHOD(thread_add_ln703_fu_692_p0);
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( exp_table1_q1 );

    SC_METHOD(thread_add_ln703_fu_692_p1);
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( exp_table1_q0 );

    SC_METHOD(thread_add_ln703_fu_692_p2);
    sensitive << ( add_ln703_fu_692_p0 );
    sensitive << ( add_ln703_fu_692_p1 );

    SC_METHOD(thread_and_ln786_1_fu_310_p2);
    sensitive << ( tmp_4_fu_288_p3 );
    sensitive << ( xor_ln786_1_fu_304_p2 );

    SC_METHOD(thread_and_ln786_2_fu_366_p2);
    sensitive << ( tmp_8_fu_344_p3 );
    sensitive << ( xor_ln786_2_fu_360_p2 );

    SC_METHOD(thread_and_ln786_3_fu_422_p2);
    sensitive << ( tmp_11_fu_400_p3 );
    sensitive << ( xor_ln786_3_fu_416_p2 );

    SC_METHOD(thread_and_ln786_4_fu_478_p2);
    sensitive << ( tmp_13_fu_456_p3 );
    sensitive << ( xor_ln786_4_fu_472_p2 );

    SC_METHOD(thread_and_ln786_fu_254_p2);
    sensitive << ( tmp_fu_232_p3 );
    sensitive << ( xor_ln786_fu_248_p2 );

    SC_METHOD(thread_ap_CS_fsm_pp0_stage0);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_block_pp0_stage0);

    SC_METHOD(thread_ap_block_pp0_stage0_11001);
    sensitive << ( ap_start );

    SC_METHOD(thread_ap_block_pp0_stage0_subdone);
    sensitive << ( ap_start );
    sensitive << ( ap_ce );

    SC_METHOD(thread_ap_block_state1_pp0_stage0_iter0);
    sensitive << ( ap_start );

    SC_METHOD(thread_ap_block_state2_pp0_stage0_iter1);

    SC_METHOD(thread_ap_block_state3_pp0_stage0_iter2);

    SC_METHOD(thread_ap_block_state4_pp0_stage0_iter3);

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter3 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_ce );

    SC_METHOD(thread_ap_enable_pp0);
    sensitive << ( ap_idle_pp0 );

    SC_METHOD(thread_ap_enable_reg_pp0_iter0);
    sensitive << ( ap_start );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_idle_pp0 );

    SC_METHOD(thread_ap_idle_pp0);
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( ap_enable_reg_pp0_iter3 );

    SC_METHOD(thread_ap_idle_pp0_0to2);
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_enable_reg_pp0_iter2 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_ce );

    SC_METHOD(thread_ap_reset_idle_pp0);
    sensitive << ( ap_start );
    sensitive << ( ap_idle_pp0_0to2 );

    SC_METHOD(thread_ap_return_0);
    sensitive << ( ap_enable_reg_pp0_iter3 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_ce );
    sensitive << ( mul_ln1118_fu_825_p2 );

    SC_METHOD(thread_ap_return_1);
    sensitive << ( ap_enable_reg_pp0_iter3 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_ce );
    sensitive << ( mul_ln1118_1_fu_832_p2 );

    SC_METHOD(thread_ap_return_2);
    sensitive << ( ap_enable_reg_pp0_iter3 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_ce );
    sensitive << ( mul_ln1118_2_fu_839_p2 );

    SC_METHOD(thread_ap_return_3);
    sensitive << ( ap_enable_reg_pp0_iter3 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_ce );
    sensitive << ( mul_ln1118_3_fu_846_p2 );

    SC_METHOD(thread_ap_return_4);
    sensitive << ( ap_enable_reg_pp0_iter3 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_ce );
    sensitive << ( mul_ln1118_4_fu_853_p2 );

    SC_METHOD(thread_exp_sum_V_fu_710_p2);
    sensitive << ( add_ln703_fu_692_p2 );
    sensitive << ( add_ln703_2_fu_704_p2 );

    SC_METHOD(thread_exp_table1_address0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( zext_ln255_fu_672_p1 );

    SC_METHOD(thread_exp_table1_address1);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( zext_ln255_1_fu_676_p1 );

    SC_METHOD(thread_exp_table1_address2);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( zext_ln255_2_fu_680_p1 );

    SC_METHOD(thread_exp_table1_address3);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( zext_ln255_3_fu_684_p1 );

    SC_METHOD(thread_exp_table1_address4);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( zext_ln255_4_fu_688_p1 );

    SC_METHOD(thread_exp_table1_ce0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_ce );

    SC_METHOD(thread_exp_table1_ce1);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_ce );

    SC_METHOD(thread_exp_table1_ce2);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_ce );

    SC_METHOD(thread_exp_table1_ce3);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_ce );

    SC_METHOD(thread_exp_table1_ce4);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_ce );

    SC_METHOD(thread_icmp_ln1496_1_fu_176_p0);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( data_2_V_read );

    SC_METHOD(thread_icmp_ln1496_1_fu_176_p1);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( data_3_V_read );

    SC_METHOD(thread_icmp_ln1496_1_fu_176_p2);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_ce );
    sensitive << ( icmp_ln1496_1_fu_176_p0 );
    sensitive << ( icmp_ln1496_1_fu_176_p1 );

    SC_METHOD(thread_icmp_ln1496_2_fu_190_p2);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_ce );
    sensitive << ( select_ln65_fu_168_p3 );
    sensitive << ( select_ln65_1_fu_182_p3 );

    SC_METHOD(thread_icmp_ln1496_3_fu_204_p1);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( data_4_V_read );

    SC_METHOD(thread_icmp_ln1496_3_fu_204_p2);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_ce );
    sensitive << ( select_ln65_2_fu_196_p3 );
    sensitive << ( icmp_ln1496_3_fu_204_p1 );

    SC_METHOD(thread_icmp_ln1496_fu_162_p0);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( data_0_V_read );

    SC_METHOD(thread_icmp_ln1496_fu_162_p1);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( data_1_V_read );

    SC_METHOD(thread_icmp_ln1496_fu_162_p2);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_ce );
    sensitive << ( icmp_ln1496_fu_162_p0 );
    sensitive << ( icmp_ln1496_fu_162_p1 );

    SC_METHOD(thread_invert_table2_address0);
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( zext_ln265_fu_726_p1 );

    SC_METHOD(thread_invert_table2_ce0);
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_ce );

    SC_METHOD(thread_mul_ln1118_1_fu_832_p1);
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter3 );
    sensitive << ( sext_ln1116_fu_731_p1 );

    SC_METHOD(thread_mul_ln1118_2_fu_839_p1);
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter3 );
    sensitive << ( sext_ln1116_fu_731_p1 );

    SC_METHOD(thread_mul_ln1118_3_fu_846_p1);
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter3 );
    sensitive << ( sext_ln1116_fu_731_p1 );

    SC_METHOD(thread_mul_ln1118_4_fu_853_p1);
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter3 );
    sensitive << ( sext_ln1116_fu_731_p1 );

    SC_METHOD(thread_mul_ln1118_fu_825_p1);
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter3 );
    sensitive << ( sext_ln1116_fu_731_p1 );

    SC_METHOD(thread_or_ln340_1_fu_328_p2);
    sensitive << ( tmp_6_fu_296_p3 );
    sensitive << ( xor_ln340_1_fu_322_p2 );

    SC_METHOD(thread_or_ln340_2_fu_384_p2);
    sensitive << ( tmp_10_fu_352_p3 );
    sensitive << ( xor_ln340_2_fu_378_p2 );

    SC_METHOD(thread_or_ln340_3_fu_440_p2);
    sensitive << ( tmp_12_fu_408_p3 );
    sensitive << ( xor_ln340_3_fu_434_p2 );

    SC_METHOD(thread_or_ln340_4_fu_496_p2);
    sensitive << ( tmp_14_fu_464_p3 );
    sensitive << ( xor_ln340_4_fu_490_p2 );

    SC_METHOD(thread_or_ln340_fu_272_p2);
    sensitive << ( tmp_2_fu_240_p3 );
    sensitive << ( xor_ln340_fu_266_p2 );

    SC_METHOD(thread_select_ln340_2_fu_546_p3);
    sensitive << ( xor_ln340_6_fu_316_p2 );
    sensitive << ( tmp_3_fu_536_p4 );

    SC_METHOD(thread_select_ln340_4_fu_580_p3);
    sensitive << ( xor_ln340_7_fu_372_p2 );
    sensitive << ( tmp_5_fu_570_p4 );

    SC_METHOD(thread_select_ln340_6_fu_614_p3);
    sensitive << ( xor_ln340_8_fu_428_p2 );
    sensitive << ( tmp_7_fu_604_p4 );

    SC_METHOD(thread_select_ln340_8_fu_648_p3);
    sensitive << ( xor_ln340_9_fu_484_p2 );
    sensitive << ( tmp_9_fu_638_p4 );

    SC_METHOD(thread_select_ln340_fu_512_p3);
    sensitive << ( xor_ln340_5_fu_260_p2 );
    sensitive << ( tmp_1_fu_502_p4 );

    SC_METHOD(thread_select_ln388_1_fu_554_p3);
    sensitive << ( tmp_3_fu_536_p4 );
    sensitive << ( and_ln786_1_fu_310_p2 );

    SC_METHOD(thread_select_ln388_2_fu_588_p3);
    sensitive << ( tmp_5_fu_570_p4 );
    sensitive << ( and_ln786_2_fu_366_p2 );

    SC_METHOD(thread_select_ln388_3_fu_622_p3);
    sensitive << ( tmp_7_fu_604_p4 );
    sensitive << ( and_ln786_3_fu_422_p2 );

    SC_METHOD(thread_select_ln388_4_fu_656_p3);
    sensitive << ( tmp_9_fu_638_p4 );
    sensitive << ( and_ln786_4_fu_478_p2 );

    SC_METHOD(thread_select_ln388_fu_520_p3);
    sensitive << ( tmp_1_fu_502_p4 );
    sensitive << ( and_ln786_fu_254_p2 );

    SC_METHOD(thread_select_ln65_1_fu_182_p1);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( data_3_V_read );

    SC_METHOD(thread_select_ln65_1_fu_182_p2);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( data_2_V_read );

    SC_METHOD(thread_select_ln65_1_fu_182_p3);
    sensitive << ( icmp_ln1496_1_fu_176_p2 );
    sensitive << ( select_ln65_1_fu_182_p1 );
    sensitive << ( select_ln65_1_fu_182_p2 );

    SC_METHOD(thread_select_ln65_2_fu_196_p3);
    sensitive << ( select_ln65_fu_168_p3 );
    sensitive << ( select_ln65_1_fu_182_p3 );
    sensitive << ( icmp_ln1496_2_fu_190_p2 );

    SC_METHOD(thread_select_ln65_fu_168_p1);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( data_1_V_read );

    SC_METHOD(thread_select_ln65_fu_168_p2);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( data_0_V_read );

    SC_METHOD(thread_select_ln65_fu_168_p3);
    sensitive << ( icmp_ln1496_fu_162_p2 );
    sensitive << ( select_ln65_fu_168_p1 );
    sensitive << ( select_ln65_fu_168_p2 );

    SC_METHOD(thread_sext_ln1116_fu_731_p1);
    sensitive << ( invert_table2_q0 );

    SC_METHOD(thread_sext_ln703_1_fu_222_p1);
    sensitive << ( x_max_V_fu_210_p3 );

    SC_METHOD(thread_sext_ln703_2_fu_278_p0);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( data_1_V_read );

    SC_METHOD(thread_sext_ln703_2_fu_278_p1);
    sensitive << ( sext_ln703_2_fu_278_p0 );

    SC_METHOD(thread_sext_ln703_3_fu_334_p0);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( data_2_V_read );

    SC_METHOD(thread_sext_ln703_3_fu_334_p1);
    sensitive << ( sext_ln703_3_fu_334_p0 );

    SC_METHOD(thread_sext_ln703_4_fu_390_p0);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( data_3_V_read );

    SC_METHOD(thread_sext_ln703_4_fu_390_p1);
    sensitive << ( sext_ln703_4_fu_390_p0 );

    SC_METHOD(thread_sext_ln703_5_fu_446_p0);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( data_4_V_read );

    SC_METHOD(thread_sext_ln703_5_fu_446_p1);
    sensitive << ( sext_ln703_5_fu_446_p0 );

    SC_METHOD(thread_sext_ln703_fu_218_p0);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( data_0_V_read );

    SC_METHOD(thread_sext_ln703_fu_218_p1);
    sensitive << ( sext_ln703_fu_218_p0 );

    SC_METHOD(thread_sub_ln1193_1_fu_282_p2);
    sensitive << ( sext_ln703_1_fu_222_p1 );
    sensitive << ( sext_ln703_2_fu_278_p1 );

    SC_METHOD(thread_sub_ln1193_2_fu_338_p2);
    sensitive << ( sext_ln703_1_fu_222_p1 );
    sensitive << ( sext_ln703_3_fu_334_p1 );

    SC_METHOD(thread_sub_ln1193_3_fu_394_p2);
    sensitive << ( sext_ln703_1_fu_222_p1 );
    sensitive << ( sext_ln703_4_fu_390_p1 );

    SC_METHOD(thread_sub_ln1193_4_fu_450_p2);
    sensitive << ( sext_ln703_1_fu_222_p1 );
    sensitive << ( sext_ln703_5_fu_446_p1 );

    SC_METHOD(thread_sub_ln1193_fu_226_p2);
    sensitive << ( sext_ln703_fu_218_p1 );
    sensitive << ( sext_ln703_1_fu_222_p1 );

    SC_METHOD(thread_tmp_10_fu_352_p3);
    sensitive << ( sub_ln1193_2_fu_338_p2 );

    SC_METHOD(thread_tmp_11_fu_400_p3);
    sensitive << ( sub_ln1193_3_fu_394_p2 );

    SC_METHOD(thread_tmp_12_fu_408_p3);
    sensitive << ( sub_ln1193_3_fu_394_p2 );

    SC_METHOD(thread_tmp_13_fu_456_p3);
    sensitive << ( sub_ln1193_4_fu_450_p2 );

    SC_METHOD(thread_tmp_14_fu_464_p3);
    sensitive << ( sub_ln1193_4_fu_450_p2 );

    SC_METHOD(thread_tmp_1_fu_502_p4);
    sensitive << ( sub_ln1193_fu_226_p2 );

    SC_METHOD(thread_tmp_2_fu_240_p3);
    sensitive << ( sub_ln1193_fu_226_p2 );

    SC_METHOD(thread_tmp_3_fu_536_p4);
    sensitive << ( sub_ln1193_1_fu_282_p2 );

    SC_METHOD(thread_tmp_4_fu_288_p3);
    sensitive << ( sub_ln1193_1_fu_282_p2 );

    SC_METHOD(thread_tmp_5_fu_570_p4);
    sensitive << ( sub_ln1193_2_fu_338_p2 );

    SC_METHOD(thread_tmp_6_fu_296_p3);
    sensitive << ( sub_ln1193_1_fu_282_p2 );

    SC_METHOD(thread_tmp_7_fu_604_p4);
    sensitive << ( sub_ln1193_3_fu_394_p2 );

    SC_METHOD(thread_tmp_8_fu_344_p3);
    sensitive << ( sub_ln1193_2_fu_338_p2 );

    SC_METHOD(thread_tmp_9_fu_638_p4);
    sensitive << ( sub_ln1193_4_fu_450_p2 );

    SC_METHOD(thread_tmp_fu_232_p3);
    sensitive << ( sub_ln1193_fu_226_p2 );

    SC_METHOD(thread_x_max_V_fu_210_p1);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( data_4_V_read );

    SC_METHOD(thread_x_max_V_fu_210_p3);
    sensitive << ( select_ln65_2_fu_196_p3 );
    sensitive << ( icmp_ln1496_3_fu_204_p2 );
    sensitive << ( x_max_V_fu_210_p1 );

    SC_METHOD(thread_xor_ln340_1_fu_322_p2);
    sensitive << ( tmp_4_fu_288_p3 );

    SC_METHOD(thread_xor_ln340_2_fu_378_p2);
    sensitive << ( tmp_8_fu_344_p3 );

    SC_METHOD(thread_xor_ln340_3_fu_434_p2);
    sensitive << ( tmp_11_fu_400_p3 );

    SC_METHOD(thread_xor_ln340_4_fu_490_p2);
    sensitive << ( tmp_13_fu_456_p3 );

    SC_METHOD(thread_xor_ln340_5_fu_260_p2);
    sensitive << ( tmp_2_fu_240_p3 );
    sensitive << ( tmp_fu_232_p3 );

    SC_METHOD(thread_xor_ln340_6_fu_316_p2);
    sensitive << ( tmp_6_fu_296_p3 );
    sensitive << ( tmp_4_fu_288_p3 );

    SC_METHOD(thread_xor_ln340_7_fu_372_p2);
    sensitive << ( tmp_10_fu_352_p3 );
    sensitive << ( tmp_8_fu_344_p3 );

    SC_METHOD(thread_xor_ln340_8_fu_428_p2);
    sensitive << ( tmp_12_fu_408_p3 );
    sensitive << ( tmp_11_fu_400_p3 );

    SC_METHOD(thread_xor_ln340_9_fu_484_p2);
    sensitive << ( tmp_14_fu_464_p3 );
    sensitive << ( tmp_13_fu_456_p3 );

    SC_METHOD(thread_xor_ln340_fu_266_p2);
    sensitive << ( tmp_fu_232_p3 );

    SC_METHOD(thread_xor_ln786_1_fu_304_p2);
    sensitive << ( tmp_6_fu_296_p3 );

    SC_METHOD(thread_xor_ln786_2_fu_360_p2);
    sensitive << ( tmp_10_fu_352_p3 );

    SC_METHOD(thread_xor_ln786_3_fu_416_p2);
    sensitive << ( tmp_12_fu_408_p3 );

    SC_METHOD(thread_xor_ln786_4_fu_472_p2);
    sensitive << ( tmp_14_fu_464_p3 );

    SC_METHOD(thread_xor_ln786_fu_248_p2);
    sensitive << ( tmp_2_fu_240_p3 );

    SC_METHOD(thread_y_V_1_fu_562_p3);
    sensitive << ( or_ln340_1_fu_328_p2 );
    sensitive << ( select_ln340_2_fu_546_p3 );
    sensitive << ( select_ln388_1_fu_554_p3 );

    SC_METHOD(thread_y_V_2_fu_596_p3);
    sensitive << ( or_ln340_2_fu_384_p2 );
    sensitive << ( select_ln340_4_fu_580_p3 );
    sensitive << ( select_ln388_2_fu_588_p3 );

    SC_METHOD(thread_y_V_3_fu_630_p3);
    sensitive << ( or_ln340_3_fu_440_p2 );
    sensitive << ( select_ln340_6_fu_614_p3 );
    sensitive << ( select_ln388_3_fu_622_p3 );

    SC_METHOD(thread_y_V_4_fu_664_p3);
    sensitive << ( or_ln340_4_fu_496_p2 );
    sensitive << ( select_ln340_8_fu_648_p3 );
    sensitive << ( select_ln388_4_fu_656_p3 );

    SC_METHOD(thread_y_V_5_fu_716_p4);
    sensitive << ( exp_sum_V_fu_710_p2 );

    SC_METHOD(thread_y_V_fu_528_p3);
    sensitive << ( or_ln340_fu_272_p2 );
    sensitive << ( select_ln340_fu_512_p3 );
    sensitive << ( select_ln388_fu_520_p3 );

    SC_METHOD(thread_zext_ln255_1_fu_676_p1);
    sensitive << ( y_V_1_reg_865 );

    SC_METHOD(thread_zext_ln255_2_fu_680_p1);
    sensitive << ( y_V_2_reg_870 );

    SC_METHOD(thread_zext_ln255_3_fu_684_p1);
    sensitive << ( y_V_3_reg_875 );

    SC_METHOD(thread_zext_ln255_4_fu_688_p1);
    sensitive << ( y_V_4_reg_880 );

    SC_METHOD(thread_zext_ln255_fu_672_p1);
    sensitive << ( y_V_reg_860 );

    SC_METHOD(thread_zext_ln265_fu_726_p1);
    sensitive << ( y_V_5_fu_716_p4 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_block_pp0_stage0_subdone );
    sensitive << ( ap_reset_idle_pp0 );

    ap_CS_fsm = "1";
    ap_enable_reg_pp0_iter1 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter2 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter3 = SC_LOGIC_0;
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "softmax_stable_ap_fixed_ap_fixed_16_6_5_3_0_softmax_config13_s_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, ap_ce, "(port)ap_ce");
    sc_trace(mVcdFile, data_0_V_read, "(port)data_0_V_read");
    sc_trace(mVcdFile, data_1_V_read, "(port)data_1_V_read");
    sc_trace(mVcdFile, data_2_V_read, "(port)data_2_V_read");
    sc_trace(mVcdFile, data_3_V_read, "(port)data_3_V_read");
    sc_trace(mVcdFile, data_4_V_read, "(port)data_4_V_read");
    sc_trace(mVcdFile, ap_return_0, "(port)ap_return_0");
    sc_trace(mVcdFile, ap_return_1, "(port)ap_return_1");
    sc_trace(mVcdFile, ap_return_2, "(port)ap_return_2");
    sc_trace(mVcdFile, ap_return_3, "(port)ap_return_3");
    sc_trace(mVcdFile, ap_return_4, "(port)ap_return_4");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_pp0_stage0, "ap_CS_fsm_pp0_stage0");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter0, "ap_enable_reg_pp0_iter0");
    sc_trace(mVcdFile, ap_block_pp0_stage0, "ap_block_pp0_stage0");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter1, "ap_enable_reg_pp0_iter1");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter2, "ap_enable_reg_pp0_iter2");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter3, "ap_enable_reg_pp0_iter3");
    sc_trace(mVcdFile, ap_idle_pp0, "ap_idle_pp0");
    sc_trace(mVcdFile, ap_block_state1_pp0_stage0_iter0, "ap_block_state1_pp0_stage0_iter0");
    sc_trace(mVcdFile, ap_block_state2_pp0_stage0_iter1, "ap_block_state2_pp0_stage0_iter1");
    sc_trace(mVcdFile, ap_block_state3_pp0_stage0_iter2, "ap_block_state3_pp0_stage0_iter2");
    sc_trace(mVcdFile, ap_block_state4_pp0_stage0_iter3, "ap_block_state4_pp0_stage0_iter3");
    sc_trace(mVcdFile, ap_block_pp0_stage0_11001, "ap_block_pp0_stage0_11001");
    sc_trace(mVcdFile, exp_table1_address0, "exp_table1_address0");
    sc_trace(mVcdFile, exp_table1_ce0, "exp_table1_ce0");
    sc_trace(mVcdFile, exp_table1_q0, "exp_table1_q0");
    sc_trace(mVcdFile, exp_table1_address1, "exp_table1_address1");
    sc_trace(mVcdFile, exp_table1_ce1, "exp_table1_ce1");
    sc_trace(mVcdFile, exp_table1_q1, "exp_table1_q1");
    sc_trace(mVcdFile, exp_table1_address2, "exp_table1_address2");
    sc_trace(mVcdFile, exp_table1_ce2, "exp_table1_ce2");
    sc_trace(mVcdFile, exp_table1_q2, "exp_table1_q2");
    sc_trace(mVcdFile, exp_table1_address3, "exp_table1_address3");
    sc_trace(mVcdFile, exp_table1_ce3, "exp_table1_ce3");
    sc_trace(mVcdFile, exp_table1_q3, "exp_table1_q3");
    sc_trace(mVcdFile, exp_table1_address4, "exp_table1_address4");
    sc_trace(mVcdFile, exp_table1_ce4, "exp_table1_ce4");
    sc_trace(mVcdFile, exp_table1_q4, "exp_table1_q4");
    sc_trace(mVcdFile, invert_table2_address0, "invert_table2_address0");
    sc_trace(mVcdFile, invert_table2_ce0, "invert_table2_ce0");
    sc_trace(mVcdFile, invert_table2_q0, "invert_table2_q0");
    sc_trace(mVcdFile, y_V_fu_528_p3, "y_V_fu_528_p3");
    sc_trace(mVcdFile, y_V_reg_860, "y_V_reg_860");
    sc_trace(mVcdFile, y_V_1_fu_562_p3, "y_V_1_fu_562_p3");
    sc_trace(mVcdFile, y_V_1_reg_865, "y_V_1_reg_865");
    sc_trace(mVcdFile, y_V_2_fu_596_p3, "y_V_2_fu_596_p3");
    sc_trace(mVcdFile, y_V_2_reg_870, "y_V_2_reg_870");
    sc_trace(mVcdFile, y_V_3_fu_630_p3, "y_V_3_fu_630_p3");
    sc_trace(mVcdFile, y_V_3_reg_875, "y_V_3_reg_875");
    sc_trace(mVcdFile, y_V_4_fu_664_p3, "y_V_4_fu_664_p3");
    sc_trace(mVcdFile, y_V_4_reg_880, "y_V_4_reg_880");
    sc_trace(mVcdFile, exp_res_0_V_reg_910, "exp_res_0_V_reg_910");
    sc_trace(mVcdFile, exp_res_1_V_reg_915, "exp_res_1_V_reg_915");
    sc_trace(mVcdFile, exp_res_2_V_reg_920, "exp_res_2_V_reg_920");
    sc_trace(mVcdFile, exp_res_3_V_reg_925, "exp_res_3_V_reg_925");
    sc_trace(mVcdFile, exp_res_4_V_reg_930, "exp_res_4_V_reg_930");
    sc_trace(mVcdFile, ap_block_pp0_stage0_subdone, "ap_block_pp0_stage0_subdone");
    sc_trace(mVcdFile, zext_ln255_fu_672_p1, "zext_ln255_fu_672_p1");
    sc_trace(mVcdFile, zext_ln255_1_fu_676_p1, "zext_ln255_1_fu_676_p1");
    sc_trace(mVcdFile, zext_ln255_2_fu_680_p1, "zext_ln255_2_fu_680_p1");
    sc_trace(mVcdFile, zext_ln255_3_fu_684_p1, "zext_ln255_3_fu_684_p1");
    sc_trace(mVcdFile, zext_ln255_4_fu_688_p1, "zext_ln255_4_fu_688_p1");
    sc_trace(mVcdFile, zext_ln265_fu_726_p1, "zext_ln265_fu_726_p1");
    sc_trace(mVcdFile, icmp_ln1496_fu_162_p0, "icmp_ln1496_fu_162_p0");
    sc_trace(mVcdFile, icmp_ln1496_fu_162_p1, "icmp_ln1496_fu_162_p1");
    sc_trace(mVcdFile, icmp_ln1496_fu_162_p2, "icmp_ln1496_fu_162_p2");
    sc_trace(mVcdFile, select_ln65_fu_168_p1, "select_ln65_fu_168_p1");
    sc_trace(mVcdFile, select_ln65_fu_168_p2, "select_ln65_fu_168_p2");
    sc_trace(mVcdFile, icmp_ln1496_1_fu_176_p0, "icmp_ln1496_1_fu_176_p0");
    sc_trace(mVcdFile, icmp_ln1496_1_fu_176_p1, "icmp_ln1496_1_fu_176_p1");
    sc_trace(mVcdFile, icmp_ln1496_1_fu_176_p2, "icmp_ln1496_1_fu_176_p2");
    sc_trace(mVcdFile, select_ln65_1_fu_182_p1, "select_ln65_1_fu_182_p1");
    sc_trace(mVcdFile, select_ln65_1_fu_182_p2, "select_ln65_1_fu_182_p2");
    sc_trace(mVcdFile, select_ln65_fu_168_p3, "select_ln65_fu_168_p3");
    sc_trace(mVcdFile, select_ln65_1_fu_182_p3, "select_ln65_1_fu_182_p3");
    sc_trace(mVcdFile, icmp_ln1496_2_fu_190_p2, "icmp_ln1496_2_fu_190_p2");
    sc_trace(mVcdFile, select_ln65_2_fu_196_p3, "select_ln65_2_fu_196_p3");
    sc_trace(mVcdFile, icmp_ln1496_3_fu_204_p1, "icmp_ln1496_3_fu_204_p1");
    sc_trace(mVcdFile, icmp_ln1496_3_fu_204_p2, "icmp_ln1496_3_fu_204_p2");
    sc_trace(mVcdFile, x_max_V_fu_210_p1, "x_max_V_fu_210_p1");
    sc_trace(mVcdFile, sext_ln703_fu_218_p0, "sext_ln703_fu_218_p0");
    sc_trace(mVcdFile, x_max_V_fu_210_p3, "x_max_V_fu_210_p3");
    sc_trace(mVcdFile, sext_ln703_fu_218_p1, "sext_ln703_fu_218_p1");
    sc_trace(mVcdFile, sext_ln703_1_fu_222_p1, "sext_ln703_1_fu_222_p1");
    sc_trace(mVcdFile, sub_ln1193_fu_226_p2, "sub_ln1193_fu_226_p2");
    sc_trace(mVcdFile, tmp_2_fu_240_p3, "tmp_2_fu_240_p3");
    sc_trace(mVcdFile, tmp_fu_232_p3, "tmp_fu_232_p3");
    sc_trace(mVcdFile, xor_ln786_fu_248_p2, "xor_ln786_fu_248_p2");
    sc_trace(mVcdFile, xor_ln340_fu_266_p2, "xor_ln340_fu_266_p2");
    sc_trace(mVcdFile, sext_ln703_2_fu_278_p0, "sext_ln703_2_fu_278_p0");
    sc_trace(mVcdFile, sext_ln703_2_fu_278_p1, "sext_ln703_2_fu_278_p1");
    sc_trace(mVcdFile, sub_ln1193_1_fu_282_p2, "sub_ln1193_1_fu_282_p2");
    sc_trace(mVcdFile, tmp_6_fu_296_p3, "tmp_6_fu_296_p3");
    sc_trace(mVcdFile, tmp_4_fu_288_p3, "tmp_4_fu_288_p3");
    sc_trace(mVcdFile, xor_ln786_1_fu_304_p2, "xor_ln786_1_fu_304_p2");
    sc_trace(mVcdFile, xor_ln340_1_fu_322_p2, "xor_ln340_1_fu_322_p2");
    sc_trace(mVcdFile, sext_ln703_3_fu_334_p0, "sext_ln703_3_fu_334_p0");
    sc_trace(mVcdFile, sext_ln703_3_fu_334_p1, "sext_ln703_3_fu_334_p1");
    sc_trace(mVcdFile, sub_ln1193_2_fu_338_p2, "sub_ln1193_2_fu_338_p2");
    sc_trace(mVcdFile, tmp_10_fu_352_p3, "tmp_10_fu_352_p3");
    sc_trace(mVcdFile, tmp_8_fu_344_p3, "tmp_8_fu_344_p3");
    sc_trace(mVcdFile, xor_ln786_2_fu_360_p2, "xor_ln786_2_fu_360_p2");
    sc_trace(mVcdFile, xor_ln340_2_fu_378_p2, "xor_ln340_2_fu_378_p2");
    sc_trace(mVcdFile, sext_ln703_4_fu_390_p0, "sext_ln703_4_fu_390_p0");
    sc_trace(mVcdFile, sext_ln703_4_fu_390_p1, "sext_ln703_4_fu_390_p1");
    sc_trace(mVcdFile, sub_ln1193_3_fu_394_p2, "sub_ln1193_3_fu_394_p2");
    sc_trace(mVcdFile, tmp_12_fu_408_p3, "tmp_12_fu_408_p3");
    sc_trace(mVcdFile, tmp_11_fu_400_p3, "tmp_11_fu_400_p3");
    sc_trace(mVcdFile, xor_ln786_3_fu_416_p2, "xor_ln786_3_fu_416_p2");
    sc_trace(mVcdFile, xor_ln340_3_fu_434_p2, "xor_ln340_3_fu_434_p2");
    sc_trace(mVcdFile, sext_ln703_5_fu_446_p0, "sext_ln703_5_fu_446_p0");
    sc_trace(mVcdFile, sext_ln703_5_fu_446_p1, "sext_ln703_5_fu_446_p1");
    sc_trace(mVcdFile, sub_ln1193_4_fu_450_p2, "sub_ln1193_4_fu_450_p2");
    sc_trace(mVcdFile, tmp_14_fu_464_p3, "tmp_14_fu_464_p3");
    sc_trace(mVcdFile, tmp_13_fu_456_p3, "tmp_13_fu_456_p3");
    sc_trace(mVcdFile, xor_ln786_4_fu_472_p2, "xor_ln786_4_fu_472_p2");
    sc_trace(mVcdFile, xor_ln340_4_fu_490_p2, "xor_ln340_4_fu_490_p2");
    sc_trace(mVcdFile, xor_ln340_5_fu_260_p2, "xor_ln340_5_fu_260_p2");
    sc_trace(mVcdFile, tmp_1_fu_502_p4, "tmp_1_fu_502_p4");
    sc_trace(mVcdFile, and_ln786_fu_254_p2, "and_ln786_fu_254_p2");
    sc_trace(mVcdFile, or_ln340_fu_272_p2, "or_ln340_fu_272_p2");
    sc_trace(mVcdFile, select_ln340_fu_512_p3, "select_ln340_fu_512_p3");
    sc_trace(mVcdFile, select_ln388_fu_520_p3, "select_ln388_fu_520_p3");
    sc_trace(mVcdFile, xor_ln340_6_fu_316_p2, "xor_ln340_6_fu_316_p2");
    sc_trace(mVcdFile, tmp_3_fu_536_p4, "tmp_3_fu_536_p4");
    sc_trace(mVcdFile, and_ln786_1_fu_310_p2, "and_ln786_1_fu_310_p2");
    sc_trace(mVcdFile, or_ln340_1_fu_328_p2, "or_ln340_1_fu_328_p2");
    sc_trace(mVcdFile, select_ln340_2_fu_546_p3, "select_ln340_2_fu_546_p3");
    sc_trace(mVcdFile, select_ln388_1_fu_554_p3, "select_ln388_1_fu_554_p3");
    sc_trace(mVcdFile, xor_ln340_7_fu_372_p2, "xor_ln340_7_fu_372_p2");
    sc_trace(mVcdFile, tmp_5_fu_570_p4, "tmp_5_fu_570_p4");
    sc_trace(mVcdFile, and_ln786_2_fu_366_p2, "and_ln786_2_fu_366_p2");
    sc_trace(mVcdFile, or_ln340_2_fu_384_p2, "or_ln340_2_fu_384_p2");
    sc_trace(mVcdFile, select_ln340_4_fu_580_p3, "select_ln340_4_fu_580_p3");
    sc_trace(mVcdFile, select_ln388_2_fu_588_p3, "select_ln388_2_fu_588_p3");
    sc_trace(mVcdFile, xor_ln340_8_fu_428_p2, "xor_ln340_8_fu_428_p2");
    sc_trace(mVcdFile, tmp_7_fu_604_p4, "tmp_7_fu_604_p4");
    sc_trace(mVcdFile, and_ln786_3_fu_422_p2, "and_ln786_3_fu_422_p2");
    sc_trace(mVcdFile, or_ln340_3_fu_440_p2, "or_ln340_3_fu_440_p2");
    sc_trace(mVcdFile, select_ln340_6_fu_614_p3, "select_ln340_6_fu_614_p3");
    sc_trace(mVcdFile, select_ln388_3_fu_622_p3, "select_ln388_3_fu_622_p3");
    sc_trace(mVcdFile, xor_ln340_9_fu_484_p2, "xor_ln340_9_fu_484_p2");
    sc_trace(mVcdFile, tmp_9_fu_638_p4, "tmp_9_fu_638_p4");
    sc_trace(mVcdFile, and_ln786_4_fu_478_p2, "and_ln786_4_fu_478_p2");
    sc_trace(mVcdFile, or_ln340_4_fu_496_p2, "or_ln340_4_fu_496_p2");
    sc_trace(mVcdFile, select_ln340_8_fu_648_p3, "select_ln340_8_fu_648_p3");
    sc_trace(mVcdFile, select_ln388_4_fu_656_p3, "select_ln388_4_fu_656_p3");
    sc_trace(mVcdFile, add_ln703_fu_692_p0, "add_ln703_fu_692_p0");
    sc_trace(mVcdFile, add_ln703_fu_692_p1, "add_ln703_fu_692_p1");
    sc_trace(mVcdFile, add_ln703_1_fu_698_p0, "add_ln703_1_fu_698_p0");
    sc_trace(mVcdFile, add_ln703_1_fu_698_p1, "add_ln703_1_fu_698_p1");
    sc_trace(mVcdFile, add_ln703_2_fu_704_p0, "add_ln703_2_fu_704_p0");
    sc_trace(mVcdFile, add_ln703_1_fu_698_p2, "add_ln703_1_fu_698_p2");
    sc_trace(mVcdFile, add_ln703_fu_692_p2, "add_ln703_fu_692_p2");
    sc_trace(mVcdFile, add_ln703_2_fu_704_p2, "add_ln703_2_fu_704_p2");
    sc_trace(mVcdFile, exp_sum_V_fu_710_p2, "exp_sum_V_fu_710_p2");
    sc_trace(mVcdFile, y_V_5_fu_716_p4, "y_V_5_fu_716_p4");
    sc_trace(mVcdFile, mul_ln1118_fu_825_p2, "mul_ln1118_fu_825_p2");
    sc_trace(mVcdFile, mul_ln1118_1_fu_832_p2, "mul_ln1118_1_fu_832_p2");
    sc_trace(mVcdFile, mul_ln1118_2_fu_839_p2, "mul_ln1118_2_fu_839_p2");
    sc_trace(mVcdFile, mul_ln1118_3_fu_846_p2, "mul_ln1118_3_fu_846_p2");
    sc_trace(mVcdFile, mul_ln1118_4_fu_853_p2, "mul_ln1118_4_fu_853_p2");
    sc_trace(mVcdFile, mul_ln1118_fu_825_p1, "mul_ln1118_fu_825_p1");
    sc_trace(mVcdFile, sext_ln1116_fu_731_p1, "sext_ln1116_fu_731_p1");
    sc_trace(mVcdFile, mul_ln1118_1_fu_832_p1, "mul_ln1118_1_fu_832_p1");
    sc_trace(mVcdFile, mul_ln1118_2_fu_839_p1, "mul_ln1118_2_fu_839_p1");
    sc_trace(mVcdFile, mul_ln1118_3_fu_846_p1, "mul_ln1118_3_fu_846_p1");
    sc_trace(mVcdFile, mul_ln1118_4_fu_853_p1, "mul_ln1118_4_fu_853_p1");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
    sc_trace(mVcdFile, ap_idle_pp0_0to2, "ap_idle_pp0_0to2");
    sc_trace(mVcdFile, ap_reset_idle_pp0, "ap_reset_idle_pp0");
    sc_trace(mVcdFile, ap_enable_pp0, "ap_enable_pp0");
#endif

    }
}

softmax_stable_ap_fixed_ap_fixed_16_6_5_3_0_softmax_config13_s::~softmax_stable_ap_fixed_ap_fixed_16_6_5_3_0_softmax_config13_s() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete exp_table1_U;
    delete invert_table2_U;
    delete myproject_mul_mul_18s_18s_30_1_1_U222;
    delete myproject_mul_mul_18s_18s_30_1_1_U223;
    delete myproject_mul_mul_18s_18s_30_1_1_U224;
    delete myproject_mul_mul_18s_18s_30_1_1_U225;
    delete myproject_mul_mul_18s_18s_30_1_1_U226;
}

void softmax_stable_ap_fixed_ap_fixed_16_6_5_3_0_softmax_config13_s::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_pp0_stage0;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter1 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
             esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0))) {
            ap_enable_reg_pp0_iter1 = ap_start.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter2 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter2 = ap_enable_reg_pp0_iter1.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter3 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter3 = ap_enable_reg_pp0_iter2.read();
        }
    }
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_ce.read(), ap_const_logic_1) && esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()))) {
        exp_res_0_V_reg_910 = exp_table1_q0.read();
        exp_res_1_V_reg_915 = exp_table1_q1.read();
        exp_res_2_V_reg_920 = exp_table1_q2.read();
        exp_res_3_V_reg_925 = exp_table1_q3.read();
        exp_res_4_V_reg_930 = exp_table1_q4.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_ce.read(), ap_const_logic_1))) {
        y_V_1_reg_865 = y_V_1_fu_562_p3.read();
        y_V_2_reg_870 = y_V_2_fu_596_p3.read();
        y_V_3_reg_875 = y_V_3_fu_630_p3.read();
        y_V_4_reg_880 = y_V_4_fu_664_p3.read();
        y_V_reg_860 = y_V_fu_528_p3.read();
    }
}

void softmax_stable_ap_fixed_ap_fixed_16_6_5_3_0_softmax_config13_s::thread_add_ln703_1_fu_698_p0() {
    add_ln703_1_fu_698_p0 = exp_table1_q4.read();
}

void softmax_stable_ap_fixed_ap_fixed_16_6_5_3_0_softmax_config13_s::thread_add_ln703_1_fu_698_p1() {
    add_ln703_1_fu_698_p1 = exp_table1_q2.read();
}

void softmax_stable_ap_fixed_ap_fixed_16_6_5_3_0_softmax_config13_s::thread_add_ln703_1_fu_698_p2() {
    add_ln703_1_fu_698_p2 = (!add_ln703_1_fu_698_p0.read().is_01() || !add_ln703_1_fu_698_p1.read().is_01())? sc_lv<18>(): (sc_bigint<18>(add_ln703_1_fu_698_p0.read()) + sc_bigint<18>(add_ln703_1_fu_698_p1.read()));
}

void softmax_stable_ap_fixed_ap_fixed_16_6_5_3_0_softmax_config13_s::thread_add_ln703_2_fu_704_p0() {
    add_ln703_2_fu_704_p0 = exp_table1_q3.read();
}

void softmax_stable_ap_fixed_ap_fixed_16_6_5_3_0_softmax_config13_s::thread_add_ln703_2_fu_704_p2() {
    add_ln703_2_fu_704_p2 = (!add_ln703_2_fu_704_p0.read().is_01() || !add_ln703_1_fu_698_p2.read().is_01())? sc_lv<18>(): (sc_bigint<18>(add_ln703_2_fu_704_p0.read()) + sc_biguint<18>(add_ln703_1_fu_698_p2.read()));
}

void softmax_stable_ap_fixed_ap_fixed_16_6_5_3_0_softmax_config13_s::thread_add_ln703_fu_692_p0() {
    add_ln703_fu_692_p0 = exp_table1_q1.read();
}

void softmax_stable_ap_fixed_ap_fixed_16_6_5_3_0_softmax_config13_s::thread_add_ln703_fu_692_p1() {
    add_ln703_fu_692_p1 = exp_table1_q0.read();
}

void softmax_stable_ap_fixed_ap_fixed_16_6_5_3_0_softmax_config13_s::thread_add_ln703_fu_692_p2() {
    add_ln703_fu_692_p2 = (!add_ln703_fu_692_p0.read().is_01() || !add_ln703_fu_692_p1.read().is_01())? sc_lv<18>(): (sc_bigint<18>(add_ln703_fu_692_p0.read()) + sc_bigint<18>(add_ln703_fu_692_p1.read()));
}

void softmax_stable_ap_fixed_ap_fixed_16_6_5_3_0_softmax_config13_s::thread_and_ln786_1_fu_310_p2() {
    and_ln786_1_fu_310_p2 = (tmp_4_fu_288_p3.read() & xor_ln786_1_fu_304_p2.read());
}

void softmax_stable_ap_fixed_ap_fixed_16_6_5_3_0_softmax_config13_s::thread_and_ln786_2_fu_366_p2() {
    and_ln786_2_fu_366_p2 = (tmp_8_fu_344_p3.read() & xor_ln786_2_fu_360_p2.read());
}

void softmax_stable_ap_fixed_ap_fixed_16_6_5_3_0_softmax_config13_s::thread_and_ln786_3_fu_422_p2() {
    and_ln786_3_fu_422_p2 = (tmp_11_fu_400_p3.read() & xor_ln786_3_fu_416_p2.read());
}

void softmax_stable_ap_fixed_ap_fixed_16_6_5_3_0_softmax_config13_s::thread_and_ln786_4_fu_478_p2() {
    and_ln786_4_fu_478_p2 = (tmp_13_fu_456_p3.read() & xor_ln786_4_fu_472_p2.read());
}

void softmax_stable_ap_fixed_ap_fixed_16_6_5_3_0_softmax_config13_s::thread_and_ln786_fu_254_p2() {
    and_ln786_fu_254_p2 = (tmp_fu_232_p3.read() & xor_ln786_fu_248_p2.read());
}

void softmax_stable_ap_fixed_ap_fixed_16_6_5_3_0_softmax_config13_s::thread_ap_CS_fsm_pp0_stage0() {
    ap_CS_fsm_pp0_stage0 = ap_CS_fsm.read()[0];
}

void softmax_stable_ap_fixed_ap_fixed_16_6_5_3_0_softmax_config13_s::thread_ap_block_pp0_stage0() {
    ap_block_pp0_stage0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void softmax_stable_ap_fixed_ap_fixed_16_6_5_3_0_softmax_config13_s::thread_ap_block_pp0_stage0_11001() {
    ap_block_pp0_stage0_11001 = (esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && esl_seteq<1,1,1>(ap_const_logic_1, ap_start.read()));
}

void softmax_stable_ap_fixed_ap_fixed_16_6_5_3_0_softmax_config13_s::thread_ap_block_pp0_stage0_subdone() {
    ap_block_pp0_stage0_subdone = ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_start.read())) || esl_seteq<1,1,1>(ap_ce.read(), ap_const_logic_0));
}

void softmax_stable_ap_fixed_ap_fixed_16_6_5_3_0_softmax_config13_s::thread_ap_block_state1_pp0_stage0_iter0() {
    ap_block_state1_pp0_stage0_iter0 = esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read());
}

void softmax_stable_ap_fixed_ap_fixed_16_6_5_3_0_softmax_config13_s::thread_ap_block_state2_pp0_stage0_iter1() {
    ap_block_state2_pp0_stage0_iter1 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void softmax_stable_ap_fixed_ap_fixed_16_6_5_3_0_softmax_config13_s::thread_ap_block_state3_pp0_stage0_iter2() {
    ap_block_state3_pp0_stage0_iter2 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void softmax_stable_ap_fixed_ap_fixed_16_6_5_3_0_softmax_config13_s::thread_ap_block_state4_pp0_stage0_iter3() {
    ap_block_state4_pp0_stage0_iter3 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void softmax_stable_ap_fixed_ap_fixed_16_6_5_3_0_softmax_config13_s::thread_ap_done() {
    if (((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_start.read()) && 
          esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0)) || 
         (esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
          esl_seteq<1,1,1>(ap_ce.read(), ap_const_logic_1) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter3.read())))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void softmax_stable_ap_fixed_ap_fixed_16_6_5_3_0_softmax_config13_s::thread_ap_enable_pp0() {
    ap_enable_pp0 = (ap_idle_pp0.read() ^ ap_const_logic_1);
}

void softmax_stable_ap_fixed_ap_fixed_16_6_5_3_0_softmax_config13_s::thread_ap_enable_reg_pp0_iter0() {
    ap_enable_reg_pp0_iter0 = ap_start.read();
}

void softmax_stable_ap_fixed_ap_fixed_16_6_5_3_0_softmax_config13_s::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_idle_pp0.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void softmax_stable_ap_fixed_ap_fixed_16_6_5_3_0_softmax_config13_s::thread_ap_idle_pp0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter2.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter3.read()))) {
        ap_idle_pp0 = ap_const_logic_1;
    } else {
        ap_idle_pp0 = ap_const_logic_0;
    }
}

void softmax_stable_ap_fixed_ap_fixed_16_6_5_3_0_softmax_config13_s::thread_ap_idle_pp0_0to2() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter2.read()))) {
        ap_idle_pp0_0to2 = ap_const_logic_1;
    } else {
        ap_idle_pp0_0to2 = ap_const_logic_0;
    }
}

void softmax_stable_ap_fixed_ap_fixed_16_6_5_3_0_softmax_config13_s::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_ce.read(), ap_const_logic_1))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void softmax_stable_ap_fixed_ap_fixed_16_6_5_3_0_softmax_config13_s::thread_ap_reset_idle_pp0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_idle_pp0_0to2.read()))) {
        ap_reset_idle_pp0 = ap_const_logic_1;
    } else {
        ap_reset_idle_pp0 = ap_const_logic_0;
    }
}

void softmax_stable_ap_fixed_ap_fixed_16_6_5_3_0_softmax_config13_s::thread_ap_return_0() {
    ap_return_0 = mul_ln1118_fu_825_p2.read().range(29, 14);
}

void softmax_stable_ap_fixed_ap_fixed_16_6_5_3_0_softmax_config13_s::thread_ap_return_1() {
    ap_return_1 = mul_ln1118_1_fu_832_p2.read().range(29, 14);
}

void softmax_stable_ap_fixed_ap_fixed_16_6_5_3_0_softmax_config13_s::thread_ap_return_2() {
    ap_return_2 = mul_ln1118_2_fu_839_p2.read().range(29, 14);
}

void softmax_stable_ap_fixed_ap_fixed_16_6_5_3_0_softmax_config13_s::thread_ap_return_3() {
    ap_return_3 = mul_ln1118_3_fu_846_p2.read().range(29, 14);
}

void softmax_stable_ap_fixed_ap_fixed_16_6_5_3_0_softmax_config13_s::thread_ap_return_4() {
    ap_return_4 = mul_ln1118_4_fu_853_p2.read().range(29, 14);
}

void softmax_stable_ap_fixed_ap_fixed_16_6_5_3_0_softmax_config13_s::thread_exp_sum_V_fu_710_p2() {
    exp_sum_V_fu_710_p2 = (!add_ln703_fu_692_p2.read().is_01() || !add_ln703_2_fu_704_p2.read().is_01())? sc_lv<18>(): (sc_biguint<18>(add_ln703_fu_692_p2.read()) + sc_biguint<18>(add_ln703_2_fu_704_p2.read()));
}

void softmax_stable_ap_fixed_ap_fixed_16_6_5_3_0_softmax_config13_s::thread_exp_table1_address0() {
    exp_table1_address0 =  (sc_lv<10>) (zext_ln255_fu_672_p1.read());
}

void softmax_stable_ap_fixed_ap_fixed_16_6_5_3_0_softmax_config13_s::thread_exp_table1_address1() {
    exp_table1_address1 =  (sc_lv<10>) (zext_ln255_1_fu_676_p1.read());
}

void softmax_stable_ap_fixed_ap_fixed_16_6_5_3_0_softmax_config13_s::thread_exp_table1_address2() {
    exp_table1_address2 =  (sc_lv<10>) (zext_ln255_2_fu_680_p1.read());
}

void softmax_stable_ap_fixed_ap_fixed_16_6_5_3_0_softmax_config13_s::thread_exp_table1_address3() {
    exp_table1_address3 =  (sc_lv<10>) (zext_ln255_3_fu_684_p1.read());
}

void softmax_stable_ap_fixed_ap_fixed_16_6_5_3_0_softmax_config13_s::thread_exp_table1_address4() {
    exp_table1_address4 =  (sc_lv<10>) (zext_ln255_4_fu_688_p1.read());
}

void softmax_stable_ap_fixed_ap_fixed_16_6_5_3_0_softmax_config13_s::thread_exp_table1_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_ce.read(), ap_const_logic_1) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()))) {
        exp_table1_ce0 = ap_const_logic_1;
    } else {
        exp_table1_ce0 = ap_const_logic_0;
    }
}

void softmax_stable_ap_fixed_ap_fixed_16_6_5_3_0_softmax_config13_s::thread_exp_table1_ce1() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_ce.read(), ap_const_logic_1) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()))) {
        exp_table1_ce1 = ap_const_logic_1;
    } else {
        exp_table1_ce1 = ap_const_logic_0;
    }
}

void softmax_stable_ap_fixed_ap_fixed_16_6_5_3_0_softmax_config13_s::thread_exp_table1_ce2() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_ce.read(), ap_const_logic_1) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()))) {
        exp_table1_ce2 = ap_const_logic_1;
    } else {
        exp_table1_ce2 = ap_const_logic_0;
    }
}

void softmax_stable_ap_fixed_ap_fixed_16_6_5_3_0_softmax_config13_s::thread_exp_table1_ce3() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_ce.read(), ap_const_logic_1) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()))) {
        exp_table1_ce3 = ap_const_logic_1;
    } else {
        exp_table1_ce3 = ap_const_logic_0;
    }
}

void softmax_stable_ap_fixed_ap_fixed_16_6_5_3_0_softmax_config13_s::thread_exp_table1_ce4() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_ce.read(), ap_const_logic_1) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()))) {
        exp_table1_ce4 = ap_const_logic_1;
    } else {
        exp_table1_ce4 = ap_const_logic_0;
    }
}

void softmax_stable_ap_fixed_ap_fixed_16_6_5_3_0_softmax_config13_s::thread_icmp_ln1496_1_fu_176_p0() {
    icmp_ln1496_1_fu_176_p0 = data_2_V_read.read();
}

void softmax_stable_ap_fixed_ap_fixed_16_6_5_3_0_softmax_config13_s::thread_icmp_ln1496_1_fu_176_p1() {
    icmp_ln1496_1_fu_176_p1 = data_3_V_read.read();
}

void softmax_stable_ap_fixed_ap_fixed_16_6_5_3_0_softmax_config13_s::thread_icmp_ln1496_1_fu_176_p2() {
    icmp_ln1496_1_fu_176_p2 = (!icmp_ln1496_1_fu_176_p0.read().is_01() || !icmp_ln1496_1_fu_176_p1.read().is_01())? sc_lv<1>(): (sc_bigint<16>(icmp_ln1496_1_fu_176_p0.read()) < sc_bigint<16>(icmp_ln1496_1_fu_176_p1.read()));
}

void softmax_stable_ap_fixed_ap_fixed_16_6_5_3_0_softmax_config13_s::thread_icmp_ln1496_2_fu_190_p2() {
    icmp_ln1496_2_fu_190_p2 = (!select_ln65_fu_168_p3.read().is_01() || !select_ln65_1_fu_182_p3.read().is_01())? sc_lv<1>(): (sc_bigint<16>(select_ln65_fu_168_p3.read()) < sc_bigint<16>(select_ln65_1_fu_182_p3.read()));
}

void softmax_stable_ap_fixed_ap_fixed_16_6_5_3_0_softmax_config13_s::thread_icmp_ln1496_3_fu_204_p1() {
    icmp_ln1496_3_fu_204_p1 = data_4_V_read.read();
}

void softmax_stable_ap_fixed_ap_fixed_16_6_5_3_0_softmax_config13_s::thread_icmp_ln1496_3_fu_204_p2() {
    icmp_ln1496_3_fu_204_p2 = (!select_ln65_2_fu_196_p3.read().is_01() || !icmp_ln1496_3_fu_204_p1.read().is_01())? sc_lv<1>(): (sc_bigint<16>(select_ln65_2_fu_196_p3.read()) < sc_bigint<16>(icmp_ln1496_3_fu_204_p1.read()));
}

void softmax_stable_ap_fixed_ap_fixed_16_6_5_3_0_softmax_config13_s::thread_icmp_ln1496_fu_162_p0() {
    icmp_ln1496_fu_162_p0 = data_0_V_read.read();
}

void softmax_stable_ap_fixed_ap_fixed_16_6_5_3_0_softmax_config13_s::thread_icmp_ln1496_fu_162_p1() {
    icmp_ln1496_fu_162_p1 = data_1_V_read.read();
}

void softmax_stable_ap_fixed_ap_fixed_16_6_5_3_0_softmax_config13_s::thread_icmp_ln1496_fu_162_p2() {
    icmp_ln1496_fu_162_p2 = (!icmp_ln1496_fu_162_p0.read().is_01() || !icmp_ln1496_fu_162_p1.read().is_01())? sc_lv<1>(): (sc_bigint<16>(icmp_ln1496_fu_162_p0.read()) < sc_bigint<16>(icmp_ln1496_fu_162_p1.read()));
}

void softmax_stable_ap_fixed_ap_fixed_16_6_5_3_0_softmax_config13_s::thread_invert_table2_address0() {
    invert_table2_address0 =  (sc_lv<10>) (zext_ln265_fu_726_p1.read());
}

void softmax_stable_ap_fixed_ap_fixed_16_6_5_3_0_softmax_config13_s::thread_invert_table2_ce0() {
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_ce.read(), ap_const_logic_1) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()))) {
        invert_table2_ce0 = ap_const_logic_1;
    } else {
        invert_table2_ce0 = ap_const_logic_0;
    }
}

void softmax_stable_ap_fixed_ap_fixed_16_6_5_3_0_softmax_config13_s::thread_mul_ln1118_1_fu_832_p1() {
    mul_ln1118_1_fu_832_p1 =  (sc_lv<18>) (sext_ln1116_fu_731_p1.read());
}

void softmax_stable_ap_fixed_ap_fixed_16_6_5_3_0_softmax_config13_s::thread_mul_ln1118_2_fu_839_p1() {
    mul_ln1118_2_fu_839_p1 =  (sc_lv<18>) (sext_ln1116_fu_731_p1.read());
}

void softmax_stable_ap_fixed_ap_fixed_16_6_5_3_0_softmax_config13_s::thread_mul_ln1118_3_fu_846_p1() {
    mul_ln1118_3_fu_846_p1 =  (sc_lv<18>) (sext_ln1116_fu_731_p1.read());
}

void softmax_stable_ap_fixed_ap_fixed_16_6_5_3_0_softmax_config13_s::thread_mul_ln1118_4_fu_853_p1() {
    mul_ln1118_4_fu_853_p1 =  (sc_lv<18>) (sext_ln1116_fu_731_p1.read());
}

void softmax_stable_ap_fixed_ap_fixed_16_6_5_3_0_softmax_config13_s::thread_mul_ln1118_fu_825_p1() {
    mul_ln1118_fu_825_p1 =  (sc_lv<18>) (sext_ln1116_fu_731_p1.read());
}

void softmax_stable_ap_fixed_ap_fixed_16_6_5_3_0_softmax_config13_s::thread_or_ln340_1_fu_328_p2() {
    or_ln340_1_fu_328_p2 = (tmp_6_fu_296_p3.read() | xor_ln340_1_fu_322_p2.read());
}

void softmax_stable_ap_fixed_ap_fixed_16_6_5_3_0_softmax_config13_s::thread_or_ln340_2_fu_384_p2() {
    or_ln340_2_fu_384_p2 = (tmp_10_fu_352_p3.read() | xor_ln340_2_fu_378_p2.read());
}

void softmax_stable_ap_fixed_ap_fixed_16_6_5_3_0_softmax_config13_s::thread_or_ln340_3_fu_440_p2() {
    or_ln340_3_fu_440_p2 = (tmp_12_fu_408_p3.read() | xor_ln340_3_fu_434_p2.read());
}

void softmax_stable_ap_fixed_ap_fixed_16_6_5_3_0_softmax_config13_s::thread_or_ln340_4_fu_496_p2() {
    or_ln340_4_fu_496_p2 = (tmp_14_fu_464_p3.read() | xor_ln340_4_fu_490_p2.read());
}

void softmax_stable_ap_fixed_ap_fixed_16_6_5_3_0_softmax_config13_s::thread_or_ln340_fu_272_p2() {
    or_ln340_fu_272_p2 = (tmp_2_fu_240_p3.read() | xor_ln340_fu_266_p2.read());
}

void softmax_stable_ap_fixed_ap_fixed_16_6_5_3_0_softmax_config13_s::thread_select_ln340_2_fu_546_p3() {
    select_ln340_2_fu_546_p3 = (!xor_ln340_6_fu_316_p2.read()[0].is_01())? sc_lv<10>(): ((xor_ln340_6_fu_316_p2.read()[0].to_bool())? ap_const_lv10_1FF: tmp_3_fu_536_p4.read());
}

void softmax_stable_ap_fixed_ap_fixed_16_6_5_3_0_softmax_config13_s::thread_select_ln340_4_fu_580_p3() {
    select_ln340_4_fu_580_p3 = (!xor_ln340_7_fu_372_p2.read()[0].is_01())? sc_lv<10>(): ((xor_ln340_7_fu_372_p2.read()[0].to_bool())? ap_const_lv10_1FF: tmp_5_fu_570_p4.read());
}

void softmax_stable_ap_fixed_ap_fixed_16_6_5_3_0_softmax_config13_s::thread_select_ln340_6_fu_614_p3() {
    select_ln340_6_fu_614_p3 = (!xor_ln340_8_fu_428_p2.read()[0].is_01())? sc_lv<10>(): ((xor_ln340_8_fu_428_p2.read()[0].to_bool())? ap_const_lv10_1FF: tmp_7_fu_604_p4.read());
}

void softmax_stable_ap_fixed_ap_fixed_16_6_5_3_0_softmax_config13_s::thread_select_ln340_8_fu_648_p3() {
    select_ln340_8_fu_648_p3 = (!xor_ln340_9_fu_484_p2.read()[0].is_01())? sc_lv<10>(): ((xor_ln340_9_fu_484_p2.read()[0].to_bool())? ap_const_lv10_1FF: tmp_9_fu_638_p4.read());
}

void softmax_stable_ap_fixed_ap_fixed_16_6_5_3_0_softmax_config13_s::thread_select_ln340_fu_512_p3() {
    select_ln340_fu_512_p3 = (!xor_ln340_5_fu_260_p2.read()[0].is_01())? sc_lv<10>(): ((xor_ln340_5_fu_260_p2.read()[0].to_bool())? ap_const_lv10_1FF: tmp_1_fu_502_p4.read());
}

void softmax_stable_ap_fixed_ap_fixed_16_6_5_3_0_softmax_config13_s::thread_select_ln388_1_fu_554_p3() {
    select_ln388_1_fu_554_p3 = (!and_ln786_1_fu_310_p2.read()[0].is_01())? sc_lv<10>(): ((and_ln786_1_fu_310_p2.read()[0].to_bool())? ap_const_lv10_200: tmp_3_fu_536_p4.read());
}

void softmax_stable_ap_fixed_ap_fixed_16_6_5_3_0_softmax_config13_s::thread_select_ln388_2_fu_588_p3() {
    select_ln388_2_fu_588_p3 = (!and_ln786_2_fu_366_p2.read()[0].is_01())? sc_lv<10>(): ((and_ln786_2_fu_366_p2.read()[0].to_bool())? ap_const_lv10_200: tmp_5_fu_570_p4.read());
}

void softmax_stable_ap_fixed_ap_fixed_16_6_5_3_0_softmax_config13_s::thread_select_ln388_3_fu_622_p3() {
    select_ln388_3_fu_622_p3 = (!and_ln786_3_fu_422_p2.read()[0].is_01())? sc_lv<10>(): ((and_ln786_3_fu_422_p2.read()[0].to_bool())? ap_const_lv10_200: tmp_7_fu_604_p4.read());
}

void softmax_stable_ap_fixed_ap_fixed_16_6_5_3_0_softmax_config13_s::thread_select_ln388_4_fu_656_p3() {
    select_ln388_4_fu_656_p3 = (!and_ln786_4_fu_478_p2.read()[0].is_01())? sc_lv<10>(): ((and_ln786_4_fu_478_p2.read()[0].to_bool())? ap_const_lv10_200: tmp_9_fu_638_p4.read());
}

void softmax_stable_ap_fixed_ap_fixed_16_6_5_3_0_softmax_config13_s::thread_select_ln388_fu_520_p3() {
    select_ln388_fu_520_p3 = (!and_ln786_fu_254_p2.read()[0].is_01())? sc_lv<10>(): ((and_ln786_fu_254_p2.read()[0].to_bool())? ap_const_lv10_200: tmp_1_fu_502_p4.read());
}

void softmax_stable_ap_fixed_ap_fixed_16_6_5_3_0_softmax_config13_s::thread_select_ln65_1_fu_182_p1() {
    select_ln65_1_fu_182_p1 = data_3_V_read.read();
}

void softmax_stable_ap_fixed_ap_fixed_16_6_5_3_0_softmax_config13_s::thread_select_ln65_1_fu_182_p2() {
    select_ln65_1_fu_182_p2 = data_2_V_read.read();
}

void softmax_stable_ap_fixed_ap_fixed_16_6_5_3_0_softmax_config13_s::thread_select_ln65_1_fu_182_p3() {
    select_ln65_1_fu_182_p3 = (!icmp_ln1496_1_fu_176_p2.read()[0].is_01())? sc_lv<16>(): ((icmp_ln1496_1_fu_176_p2.read()[0].to_bool())? select_ln65_1_fu_182_p1.read(): select_ln65_1_fu_182_p2.read());
}

void softmax_stable_ap_fixed_ap_fixed_16_6_5_3_0_softmax_config13_s::thread_select_ln65_2_fu_196_p3() {
    select_ln65_2_fu_196_p3 = (!icmp_ln1496_2_fu_190_p2.read()[0].is_01())? sc_lv<16>(): ((icmp_ln1496_2_fu_190_p2.read()[0].to_bool())? select_ln65_1_fu_182_p3.read(): select_ln65_fu_168_p3.read());
}

void softmax_stable_ap_fixed_ap_fixed_16_6_5_3_0_softmax_config13_s::thread_select_ln65_fu_168_p1() {
    select_ln65_fu_168_p1 = data_1_V_read.read();
}

void softmax_stable_ap_fixed_ap_fixed_16_6_5_3_0_softmax_config13_s::thread_select_ln65_fu_168_p2() {
    select_ln65_fu_168_p2 = data_0_V_read.read();
}

void softmax_stable_ap_fixed_ap_fixed_16_6_5_3_0_softmax_config13_s::thread_select_ln65_fu_168_p3() {
    select_ln65_fu_168_p3 = (!icmp_ln1496_fu_162_p2.read()[0].is_01())? sc_lv<16>(): ((icmp_ln1496_fu_162_p2.read()[0].to_bool())? select_ln65_fu_168_p1.read(): select_ln65_fu_168_p2.read());
}

void softmax_stable_ap_fixed_ap_fixed_16_6_5_3_0_softmax_config13_s::thread_sext_ln1116_fu_731_p1() {
    sext_ln1116_fu_731_p1 = esl_sext<30,18>(invert_table2_q0.read());
}

void softmax_stable_ap_fixed_ap_fixed_16_6_5_3_0_softmax_config13_s::thread_sext_ln703_1_fu_222_p1() {
    sext_ln703_1_fu_222_p1 = esl_sext<17,16>(x_max_V_fu_210_p3.read());
}

void softmax_stable_ap_fixed_ap_fixed_16_6_5_3_0_softmax_config13_s::thread_sext_ln703_2_fu_278_p0() {
    sext_ln703_2_fu_278_p0 = data_1_V_read.read();
}

void softmax_stable_ap_fixed_ap_fixed_16_6_5_3_0_softmax_config13_s::thread_sext_ln703_2_fu_278_p1() {
    sext_ln703_2_fu_278_p1 = esl_sext<17,16>(sext_ln703_2_fu_278_p0.read());
}

void softmax_stable_ap_fixed_ap_fixed_16_6_5_3_0_softmax_config13_s::thread_sext_ln703_3_fu_334_p0() {
    sext_ln703_3_fu_334_p0 = data_2_V_read.read();
}

void softmax_stable_ap_fixed_ap_fixed_16_6_5_3_0_softmax_config13_s::thread_sext_ln703_3_fu_334_p1() {
    sext_ln703_3_fu_334_p1 = esl_sext<17,16>(sext_ln703_3_fu_334_p0.read());
}

void softmax_stable_ap_fixed_ap_fixed_16_6_5_3_0_softmax_config13_s::thread_sext_ln703_4_fu_390_p0() {
    sext_ln703_4_fu_390_p0 = data_3_V_read.read();
}

void softmax_stable_ap_fixed_ap_fixed_16_6_5_3_0_softmax_config13_s::thread_sext_ln703_4_fu_390_p1() {
    sext_ln703_4_fu_390_p1 = esl_sext<17,16>(sext_ln703_4_fu_390_p0.read());
}

void softmax_stable_ap_fixed_ap_fixed_16_6_5_3_0_softmax_config13_s::thread_sext_ln703_5_fu_446_p0() {
    sext_ln703_5_fu_446_p0 = data_4_V_read.read();
}

void softmax_stable_ap_fixed_ap_fixed_16_6_5_3_0_softmax_config13_s::thread_sext_ln703_5_fu_446_p1() {
    sext_ln703_5_fu_446_p1 = esl_sext<17,16>(sext_ln703_5_fu_446_p0.read());
}

void softmax_stable_ap_fixed_ap_fixed_16_6_5_3_0_softmax_config13_s::thread_sext_ln703_fu_218_p0() {
    sext_ln703_fu_218_p0 = data_0_V_read.read();
}

void softmax_stable_ap_fixed_ap_fixed_16_6_5_3_0_softmax_config13_s::thread_sext_ln703_fu_218_p1() {
    sext_ln703_fu_218_p1 = esl_sext<17,16>(sext_ln703_fu_218_p0.read());
}

void softmax_stable_ap_fixed_ap_fixed_16_6_5_3_0_softmax_config13_s::thread_sub_ln1193_1_fu_282_p2() {
    sub_ln1193_1_fu_282_p2 = (!sext_ln703_2_fu_278_p1.read().is_01() || !sext_ln703_1_fu_222_p1.read().is_01())? sc_lv<17>(): (sc_bigint<17>(sext_ln703_2_fu_278_p1.read()) - sc_bigint<17>(sext_ln703_1_fu_222_p1.read()));
}

void softmax_stable_ap_fixed_ap_fixed_16_6_5_3_0_softmax_config13_s::thread_sub_ln1193_2_fu_338_p2() {
    sub_ln1193_2_fu_338_p2 = (!sext_ln703_3_fu_334_p1.read().is_01() || !sext_ln703_1_fu_222_p1.read().is_01())? sc_lv<17>(): (sc_bigint<17>(sext_ln703_3_fu_334_p1.read()) - sc_bigint<17>(sext_ln703_1_fu_222_p1.read()));
}

void softmax_stable_ap_fixed_ap_fixed_16_6_5_3_0_softmax_config13_s::thread_sub_ln1193_3_fu_394_p2() {
    sub_ln1193_3_fu_394_p2 = (!sext_ln703_4_fu_390_p1.read().is_01() || !sext_ln703_1_fu_222_p1.read().is_01())? sc_lv<17>(): (sc_bigint<17>(sext_ln703_4_fu_390_p1.read()) - sc_bigint<17>(sext_ln703_1_fu_222_p1.read()));
}

void softmax_stable_ap_fixed_ap_fixed_16_6_5_3_0_softmax_config13_s::thread_sub_ln1193_4_fu_450_p2() {
    sub_ln1193_4_fu_450_p2 = (!sext_ln703_5_fu_446_p1.read().is_01() || !sext_ln703_1_fu_222_p1.read().is_01())? sc_lv<17>(): (sc_bigint<17>(sext_ln703_5_fu_446_p1.read()) - sc_bigint<17>(sext_ln703_1_fu_222_p1.read()));
}

void softmax_stable_ap_fixed_ap_fixed_16_6_5_3_0_softmax_config13_s::thread_sub_ln1193_fu_226_p2() {
    sub_ln1193_fu_226_p2 = (!sext_ln703_fu_218_p1.read().is_01() || !sext_ln703_1_fu_222_p1.read().is_01())? sc_lv<17>(): (sc_bigint<17>(sext_ln703_fu_218_p1.read()) - sc_bigint<17>(sext_ln703_1_fu_222_p1.read()));
}

void softmax_stable_ap_fixed_ap_fixed_16_6_5_3_0_softmax_config13_s::thread_tmp_10_fu_352_p3() {
    tmp_10_fu_352_p3 = sub_ln1193_2_fu_338_p2.read().range(15, 15);
}

void softmax_stable_ap_fixed_ap_fixed_16_6_5_3_0_softmax_config13_s::thread_tmp_11_fu_400_p3() {
    tmp_11_fu_400_p3 = sub_ln1193_3_fu_394_p2.read().range(16, 16);
}

void softmax_stable_ap_fixed_ap_fixed_16_6_5_3_0_softmax_config13_s::thread_tmp_12_fu_408_p3() {
    tmp_12_fu_408_p3 = sub_ln1193_3_fu_394_p2.read().range(15, 15);
}

void softmax_stable_ap_fixed_ap_fixed_16_6_5_3_0_softmax_config13_s::thread_tmp_13_fu_456_p3() {
    tmp_13_fu_456_p3 = sub_ln1193_4_fu_450_p2.read().range(16, 16);
}

void softmax_stable_ap_fixed_ap_fixed_16_6_5_3_0_softmax_config13_s::thread_tmp_14_fu_464_p3() {
    tmp_14_fu_464_p3 = sub_ln1193_4_fu_450_p2.read().range(15, 15);
}

void softmax_stable_ap_fixed_ap_fixed_16_6_5_3_0_softmax_config13_s::thread_tmp_1_fu_502_p4() {
    tmp_1_fu_502_p4 = sub_ln1193_fu_226_p2.read().range(15, 6);
}

void softmax_stable_ap_fixed_ap_fixed_16_6_5_3_0_softmax_config13_s::thread_tmp_2_fu_240_p3() {
    tmp_2_fu_240_p3 = sub_ln1193_fu_226_p2.read().range(15, 15);
}

void softmax_stable_ap_fixed_ap_fixed_16_6_5_3_0_softmax_config13_s::thread_tmp_3_fu_536_p4() {
    tmp_3_fu_536_p4 = sub_ln1193_1_fu_282_p2.read().range(15, 6);
}

void softmax_stable_ap_fixed_ap_fixed_16_6_5_3_0_softmax_config13_s::thread_tmp_4_fu_288_p3() {
    tmp_4_fu_288_p3 = sub_ln1193_1_fu_282_p2.read().range(16, 16);
}

void softmax_stable_ap_fixed_ap_fixed_16_6_5_3_0_softmax_config13_s::thread_tmp_5_fu_570_p4() {
    tmp_5_fu_570_p4 = sub_ln1193_2_fu_338_p2.read().range(15, 6);
}

void softmax_stable_ap_fixed_ap_fixed_16_6_5_3_0_softmax_config13_s::thread_tmp_6_fu_296_p3() {
    tmp_6_fu_296_p3 = sub_ln1193_1_fu_282_p2.read().range(15, 15);
}

void softmax_stable_ap_fixed_ap_fixed_16_6_5_3_0_softmax_config13_s::thread_tmp_7_fu_604_p4() {
    tmp_7_fu_604_p4 = sub_ln1193_3_fu_394_p2.read().range(15, 6);
}

void softmax_stable_ap_fixed_ap_fixed_16_6_5_3_0_softmax_config13_s::thread_tmp_8_fu_344_p3() {
    tmp_8_fu_344_p3 = sub_ln1193_2_fu_338_p2.read().range(16, 16);
}

void softmax_stable_ap_fixed_ap_fixed_16_6_5_3_0_softmax_config13_s::thread_tmp_9_fu_638_p4() {
    tmp_9_fu_638_p4 = sub_ln1193_4_fu_450_p2.read().range(15, 6);
}

void softmax_stable_ap_fixed_ap_fixed_16_6_5_3_0_softmax_config13_s::thread_tmp_fu_232_p3() {
    tmp_fu_232_p3 = sub_ln1193_fu_226_p2.read().range(16, 16);
}

void softmax_stable_ap_fixed_ap_fixed_16_6_5_3_0_softmax_config13_s::thread_x_max_V_fu_210_p1() {
    x_max_V_fu_210_p1 = data_4_V_read.read();
}

void softmax_stable_ap_fixed_ap_fixed_16_6_5_3_0_softmax_config13_s::thread_x_max_V_fu_210_p3() {
    x_max_V_fu_210_p3 = (!icmp_ln1496_3_fu_204_p2.read()[0].is_01())? sc_lv<16>(): ((icmp_ln1496_3_fu_204_p2.read()[0].to_bool())? x_max_V_fu_210_p1.read(): select_ln65_2_fu_196_p3.read());
}

void softmax_stable_ap_fixed_ap_fixed_16_6_5_3_0_softmax_config13_s::thread_xor_ln340_1_fu_322_p2() {
    xor_ln340_1_fu_322_p2 = (tmp_4_fu_288_p3.read() ^ ap_const_lv1_1);
}

void softmax_stable_ap_fixed_ap_fixed_16_6_5_3_0_softmax_config13_s::thread_xor_ln340_2_fu_378_p2() {
    xor_ln340_2_fu_378_p2 = (tmp_8_fu_344_p3.read() ^ ap_const_lv1_1);
}

void softmax_stable_ap_fixed_ap_fixed_16_6_5_3_0_softmax_config13_s::thread_xor_ln340_3_fu_434_p2() {
    xor_ln340_3_fu_434_p2 = (tmp_11_fu_400_p3.read() ^ ap_const_lv1_1);
}

void softmax_stable_ap_fixed_ap_fixed_16_6_5_3_0_softmax_config13_s::thread_xor_ln340_4_fu_490_p2() {
    xor_ln340_4_fu_490_p2 = (tmp_13_fu_456_p3.read() ^ ap_const_lv1_1);
}

void softmax_stable_ap_fixed_ap_fixed_16_6_5_3_0_softmax_config13_s::thread_xor_ln340_5_fu_260_p2() {
    xor_ln340_5_fu_260_p2 = (tmp_fu_232_p3.read() ^ tmp_2_fu_240_p3.read());
}

void softmax_stable_ap_fixed_ap_fixed_16_6_5_3_0_softmax_config13_s::thread_xor_ln340_6_fu_316_p2() {
    xor_ln340_6_fu_316_p2 = (tmp_4_fu_288_p3.read() ^ tmp_6_fu_296_p3.read());
}

void softmax_stable_ap_fixed_ap_fixed_16_6_5_3_0_softmax_config13_s::thread_xor_ln340_7_fu_372_p2() {
    xor_ln340_7_fu_372_p2 = (tmp_8_fu_344_p3.read() ^ tmp_10_fu_352_p3.read());
}

void softmax_stable_ap_fixed_ap_fixed_16_6_5_3_0_softmax_config13_s::thread_xor_ln340_8_fu_428_p2() {
    xor_ln340_8_fu_428_p2 = (tmp_11_fu_400_p3.read() ^ tmp_12_fu_408_p3.read());
}

void softmax_stable_ap_fixed_ap_fixed_16_6_5_3_0_softmax_config13_s::thread_xor_ln340_9_fu_484_p2() {
    xor_ln340_9_fu_484_p2 = (tmp_13_fu_456_p3.read() ^ tmp_14_fu_464_p3.read());
}

void softmax_stable_ap_fixed_ap_fixed_16_6_5_3_0_softmax_config13_s::thread_xor_ln340_fu_266_p2() {
    xor_ln340_fu_266_p2 = (tmp_fu_232_p3.read() ^ ap_const_lv1_1);
}

void softmax_stable_ap_fixed_ap_fixed_16_6_5_3_0_softmax_config13_s::thread_xor_ln786_1_fu_304_p2() {
    xor_ln786_1_fu_304_p2 = (tmp_6_fu_296_p3.read() ^ ap_const_lv1_1);
}

void softmax_stable_ap_fixed_ap_fixed_16_6_5_3_0_softmax_config13_s::thread_xor_ln786_2_fu_360_p2() {
    xor_ln786_2_fu_360_p2 = (tmp_10_fu_352_p3.read() ^ ap_const_lv1_1);
}

void softmax_stable_ap_fixed_ap_fixed_16_6_5_3_0_softmax_config13_s::thread_xor_ln786_3_fu_416_p2() {
    xor_ln786_3_fu_416_p2 = (tmp_12_fu_408_p3.read() ^ ap_const_lv1_1);
}

void softmax_stable_ap_fixed_ap_fixed_16_6_5_3_0_softmax_config13_s::thread_xor_ln786_4_fu_472_p2() {
    xor_ln786_4_fu_472_p2 = (tmp_14_fu_464_p3.read() ^ ap_const_lv1_1);
}

void softmax_stable_ap_fixed_ap_fixed_16_6_5_3_0_softmax_config13_s::thread_xor_ln786_fu_248_p2() {
    xor_ln786_fu_248_p2 = (tmp_2_fu_240_p3.read() ^ ap_const_lv1_1);
}

void softmax_stable_ap_fixed_ap_fixed_16_6_5_3_0_softmax_config13_s::thread_y_V_1_fu_562_p3() {
    y_V_1_fu_562_p3 = (!or_ln340_1_fu_328_p2.read()[0].is_01())? sc_lv<10>(): ((or_ln340_1_fu_328_p2.read()[0].to_bool())? select_ln340_2_fu_546_p3.read(): select_ln388_1_fu_554_p3.read());
}

void softmax_stable_ap_fixed_ap_fixed_16_6_5_3_0_softmax_config13_s::thread_y_V_2_fu_596_p3() {
    y_V_2_fu_596_p3 = (!or_ln340_2_fu_384_p2.read()[0].is_01())? sc_lv<10>(): ((or_ln340_2_fu_384_p2.read()[0].to_bool())? select_ln340_4_fu_580_p3.read(): select_ln388_2_fu_588_p3.read());
}

void softmax_stable_ap_fixed_ap_fixed_16_6_5_3_0_softmax_config13_s::thread_y_V_3_fu_630_p3() {
    y_V_3_fu_630_p3 = (!or_ln340_3_fu_440_p2.read()[0].is_01())? sc_lv<10>(): ((or_ln340_3_fu_440_p2.read()[0].to_bool())? select_ln340_6_fu_614_p3.read(): select_ln388_3_fu_622_p3.read());
}

void softmax_stable_ap_fixed_ap_fixed_16_6_5_3_0_softmax_config13_s::thread_y_V_4_fu_664_p3() {
    y_V_4_fu_664_p3 = (!or_ln340_4_fu_496_p2.read()[0].is_01())? sc_lv<10>(): ((or_ln340_4_fu_496_p2.read()[0].to_bool())? select_ln340_8_fu_648_p3.read(): select_ln388_4_fu_656_p3.read());
}

void softmax_stable_ap_fixed_ap_fixed_16_6_5_3_0_softmax_config13_s::thread_y_V_5_fu_716_p4() {
    y_V_5_fu_716_p4 = exp_sum_V_fu_710_p2.read().range(17, 8);
}

void softmax_stable_ap_fixed_ap_fixed_16_6_5_3_0_softmax_config13_s::thread_y_V_fu_528_p3() {
    y_V_fu_528_p3 = (!or_ln340_fu_272_p2.read()[0].is_01())? sc_lv<10>(): ((or_ln340_fu_272_p2.read()[0].to_bool())? select_ln340_fu_512_p3.read(): select_ln388_fu_520_p3.read());
}

void softmax_stable_ap_fixed_ap_fixed_16_6_5_3_0_softmax_config13_s::thread_zext_ln255_1_fu_676_p1() {
    zext_ln255_1_fu_676_p1 = esl_zext<64,10>(y_V_1_reg_865.read());
}

void softmax_stable_ap_fixed_ap_fixed_16_6_5_3_0_softmax_config13_s::thread_zext_ln255_2_fu_680_p1() {
    zext_ln255_2_fu_680_p1 = esl_zext<64,10>(y_V_2_reg_870.read());
}

void softmax_stable_ap_fixed_ap_fixed_16_6_5_3_0_softmax_config13_s::thread_zext_ln255_3_fu_684_p1() {
    zext_ln255_3_fu_684_p1 = esl_zext<64,10>(y_V_3_reg_875.read());
}

void softmax_stable_ap_fixed_ap_fixed_16_6_5_3_0_softmax_config13_s::thread_zext_ln255_4_fu_688_p1() {
    zext_ln255_4_fu_688_p1 = esl_zext<64,10>(y_V_4_reg_880.read());
}

void softmax_stable_ap_fixed_ap_fixed_16_6_5_3_0_softmax_config13_s::thread_zext_ln255_fu_672_p1() {
    zext_ln255_fu_672_p1 = esl_zext<64,10>(y_V_reg_860.read());
}

void softmax_stable_ap_fixed_ap_fixed_16_6_5_3_0_softmax_config13_s::thread_zext_ln265_fu_726_p1() {
    zext_ln265_fu_726_p1 = esl_zext<64,10>(y_V_5_fu_716_p4.read());
}

void softmax_stable_ap_fixed_ap_fixed_16_6_5_3_0_softmax_config13_s::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
break;
        default : 
            ap_NS_fsm = "X";
            break;
    }
}

}

